/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/adminuser/Nim/lib -o /home/adminuser/awknim/nimcache/awknim.o /home/adminuser/awknim/nimcache/awknim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Option143524 Option143524;
typedef struct Regexmatch141004 Regexmatch141004;
typedef struct RegexHEX3Aobjecttype141019 RegexHEX3Aobjecttype141019;
typedef struct TY141054 TY141054;
typedef struct Slice90081 Slice90081;
typedef struct Option141225 Option141225;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TSafePoint TSafePoint;
typedef struct Cell47905 Cell47905;
typedef struct Cellset47917 Cellset47917;
typedef struct Gcheap50418 Gcheap50418;
typedef struct Gcstack50416 Gcstack50416;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50414 Gcstat50414;
typedef struct TY15805 TY15805;
typedef struct Pcre94258 Pcre94258;
typedef struct Extradata94270 Extradata94270;
typedef struct Table141032 Table141032;
typedef struct Keyvaluepairseq141035 Keyvaluepairseq141035;
typedef struct Slice141059 Slice141059;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
typedef struct Keyvaluepair141038 Keyvaluepair141038;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Regexmatch141004  {
RegexHEX3Aobjecttype141019* pattern;
NimStringDesc* str;
TY141054* pcrematchbounds;
};
struct  Option143524  {
Regexmatch141004 val;
NIM_BOOL has;
};
struct  Slice90081  {
NI a;
NI b;
};
struct  Option141225  {
Slice90081 val;
NIM_BOOL has;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY17811;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY17811 raiseAction;
};
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30088  {
NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50418  {
Gcstack50416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50414 stat;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Table141032  {
Keyvaluepairseq141035* data;
NI counter;
};
struct  RegexHEX3Aobjecttype141019  {
NimStringDesc* pattern;
Pcre94258* pcreobj;
Extradata94270* pcreextra;
Table141032 capturenametoid;
};
struct  Slice141059  {
int a;
int b;
};
struct  Gcstack50416  {
Gcstack50416* prev;
Gcstack50416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30019[8];
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {
NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {
TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct  Pcre94258  {
char dummy;
};
struct  Extradata94270  {
long flags;
void* studydata;
long matchlimit;
void* calloutdata;
void* tables;
long matchlimitrecursion;
void* mark;
void* executablejit;
};
struct Keyvaluepair141038 {
NI Field0;
NimStringDesc* Field1;
NI Field2;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
struct TY15805 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY141054 {
  TGenericSeq Sup;
  Slice141059 data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq141035 {
  TGenericSeq Sup;
  Keyvaluepair141038 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, match_145001)(NimStringDesc* source, NimStringDesc* pattern);
N_NIMCALL(void, find_143831)(NimStringDesc* str, RegexHEX3Aobjecttype141019* pattern, NI start, NI endpos, Option143524* Result);
N_NIMCALL(RegexHEX3Aobjecttype141019*, re_143506)(NimStringDesc* pattern_143508);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(NIM_BOOL, issome_143693)(Option143524* self);
N_NIMCALL(Slice90081, get_141288)(Option141225* self);
N_NIMCALL(Option141225, HEX5BHEX5D_141213)(Regexmatch141004* pattern_141215, NI i);
N_NIMCALL(void, capturebounds_141205)(Regexmatch141004* pattern, Regexmatch141004* Result);
N_NIMCALL(void, get_143701)(Option143524* self, Regexmatch141004* Result);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, match_145037)(NimStringDesc* source, NimStringDesc* pattern, NimStringDesc** dest);
N_NIMCALL(NimStringDesc*, HEX5BHEX5D_141272)(Regexmatch141004* pattern_141274, NI i);
N_NIMCALL(void, captures_141209)(Regexmatch141004* pattern, Regexmatch141004* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NIM_BOOL, HEX7E_145119)(NimStringDesc* source, NimStringDesc* pattern);
N_NIMCALL(NIM_BOOL, HEX21HEX7E_145134)(NimStringDesc* source, NimStringDesc* pattern);
N_NIMCALL(NIM_BOOL, HEX3EHEX2A_145149)(NimStringDesc* text_145151, NimStringDesc* filename);
N_NIMCALL(void, writefile_15469)(NimStringDesc* filename, NimStringDesc* content);
N_NIMCALL(NIM_BOOL, HEX3EHEX3E_145155)(NimStringDesc* text_145157, NimStringDesc* filename);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(FILE*, open_15417)(NimStringDesc* filename, NU8 mode, NI bufsize);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_54419)(Cell47905* c);
static N_INLINE(NIM_BOOL, canbecycleroot_52058)(Cell47905* c);
static N_INLINE(void, rtladdcycleroot_52820)(Cell47905* c);
N_NOINLINE(void, incl_48647)(Cellset47917* s, Cell47905* cell);
static N_INLINE(Cell47905*, usrtocell_52040)(void* usr);
static N_INLINE(void, decref_54001)(Cell47905* c);
static N_INLINE(void, rtladdzct_53601)(Cell47905* c);
N_NOINLINE(void, addzct_52017)(Cellseq47921* s, Cell47905* c);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, write_15489)(FILE* f, NimStringDesc* s);
N_NIMCALL(NI, splitawkalt_145173)(NimStringDesc* source, TY15805** dest, NimStringDesc* match);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_86004, TNimType* mt);
N_NIMCALL(TY15805*, split_143894)(NimStringDesc* str, RegexHEX3Aobjecttype141019* pattern, NI maxsplit, NI start);
N_NIMCALL(NimStringDesc*, gsub_145202)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc** source);
N_NIMCALL(NimStringDesc*, replace_144419)(NimStringDesc* str, RegexHEX3Aobjecttype141019* pattern, NimStringDesc* sub);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, gsub_145209)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc* source);
N_NIMCALL(void, insert_145248)(TY15805** x, NimStringDesc* item, NI i);
N_NIMCALL(void, delete_145804)(TY15805** x, NI i);
N_NIMCALL(NI, patsplit_145215)(NimStringDesc* source, TY15805** field, NimStringDesc* pattern);
N_NIMCALL(NIM_BOOL, matchescrlf_141128)(RegexHEX3Aobjecttype141019* pattern);
N_NIMCALL(unsigned long, getinfo_141133)(RegexHEX3Aobjecttype141019* pattern, int opt);
N_NIMCALL(Slice90081, matchbounds_141309)(Regexmatch141004* pattern);
N_NIMCALL(void, matchimpl_143513)(NimStringDesc* str, RegexHEX3Aobjecttype141019* pattern, NI start, NI endpos, NI flags, Option143524* Result);
N_NIMCALL(NIM_BOOL, isnone_143709)(Option143524* self);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, runelenat_126392)(NimStringDesc* s, NI i);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, failedassertimpl_90839)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, match_141305)(Regexmatch141004* pattern);
N_NIMCALL(NI, patsplit_146436)(NimStringDesc* source, TY15805** field, NimStringDesc* pattern, TY15805** sep);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_81210, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NimStringDesc*, unpatsplit_146594)(TY15805* field, TY15805* sep);
N_NIMCALL(TY15805*, newseq_146679)(NI len);
N_NIMCALL(NimStringDesc*, sub_146659)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc** source);
N_NIMCALL(NimStringDesc*, sub_146708)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc* source);
N_NIMCALL(NimStringDesc*, sub_146746)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc** source, NI occurance);
N_NIMCALL(NimStringDesc*, sub_146787)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc* source, NI occurance);
N_NIMCALL(NI, index_146827)(NimStringDesc* source, NimStringDesc* target);
N_NIMCALL(NI, nsuFindStr)(NimStringDesc* s, NimStringDesc* sub, NI start);
N_NIMCALL(NimStringDesc*, substrawk_146832)(NimStringDesc* source, NI* a, NI aLen0);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
STRING_LITERAL(TMP537, "(?s)", 4);
STRING_LITERAL(TMP540, "\012", 1);
STRING_LITERAL(TMP543, "", 0);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[1];
} CNSTSEQ545 = {{1, 1}, {((NimStringDesc*) &TMP543)}};
NIM_CONST TY15805* TMP542 = ((TY15805*)&CNSTSEQ545);
STRING_LITERAL(TMP557, "offset <= strlen ", 17);
extern TFrame* frameptr_19436;
extern TSafePoint* exchandler_19437;
extern Exception* currexception_19439;
extern Gcheap50418 gch_50459;
extern TNimType NTI15805; /* seq[string] */

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(NI, match_145001)(NimStringDesc* source, NimStringDesc* pattern) {
	NI result;
	Option143524 found;
	NimStringDesc* LOC13;
	RegexHEX3Aobjecttype141019* LOC14;
	nimfr("match", "awknim.nim")
{	result = 0;
	nimln(47, "awknim.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((source ? source->Sup.len : 0) < ((NI) 1));
		if (!(LOC3)) goto LA4;
		LOC3 = ((pattern ? pattern->Sup.len : 0) < ((NI) 1));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(48, "awknim.nim");
		result = ((NI) 1);
		goto BeforeRet;
	}
	LA5: ;
	nimln(49, "awknim.nim");
	{
		NIM_BOOL LOC9;
		LOC9 = 0;
		LOC9 = ((source ? source->Sup.len : 0) < ((NI) 1));
		if (LOC9) goto LA10;
		LOC9 = ((pattern ? pattern->Sup.len : 0) < ((NI) 1));
		LA10: ;
		if (!LOC9) goto LA11;
		nimln(50, "awknim.nim");
		result = ((NI) 0);
		goto BeforeRet;
	}
	LA11: ;
	memset((void*)(&found), 0, sizeof(found));
	nimln(52, "awknim.nim");
	LOC13 = 0;
	LOC13 = rawNewString(pattern->Sup.len + 4);
appendString(LOC13, ((NimStringDesc*) &TMP537));
appendString(LOC13, pattern);
	LOC14 = 0;
	LOC14 = re_143506(LOC13);
	chckNil((void*)(&found));
	memset((void*)(&found), 0, sizeof(found));
	find_143831(source, LOC14, ((NI) 0), ((NI) IL64(9223372036854775807)), (&found));
	nimln(53, "awknim.nim");
	{
		NIM_BOOL LOC17;
		Slice90081 j;
		Regexmatch141004 LOC20;
		Regexmatch141004 LOC21;
		Option141225 LOC22;
		NI TMP538;
		LOC17 = 0;
		LOC17 = issome_143693((&found));
		if (!LOC17) goto LA18;
		memset((void*)(&j), 0, sizeof(j));
		nimln(55, "awknim.nim");
		memset((void*)(&LOC20), 0, sizeof(LOC20));
		get_143701((&found), (&LOC20));
		memset((void*)(&LOC21), 0, sizeof(LOC21));
		capturebounds_141205((&LOC20), (&LOC21));
		LOC22 = HEX5BHEX5D_141213((&LOC21), ((NI) -1));
		j = get_141288((&LOC22));
		nimln(56, "awknim.nim");
		TMP538 = addInt(j.a, ((NI) 1));
		result = (NI)(TMP538);
		goto BeforeRet;
	}
	goto LA15;
	LA18: ;
	{
		nimln(58, "awknim.nim");
		result = ((NI) 0);
		goto BeforeRet;
	}
	LA15: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, match_145037)(NimStringDesc* source, NimStringDesc* pattern, NimStringDesc** dest) {
	NI result;
	Option143524 found;
	NimStringDesc* LOC13;
	RegexHEX3Aobjecttype141019* LOC14;
	nimfr("match", "awknim.nim")
{	result = 0;
	nimln(61, "awknim.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((source ? source->Sup.len : 0) < ((NI) 1));
		if (!(LOC3)) goto LA4;
		LOC3 = ((pattern ? pattern->Sup.len : 0) < ((NI) 1));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(62, "awknim.nim");
		result = ((NI) 1);
		goto BeforeRet;
	}
	LA5: ;
	nimln(63, "awknim.nim");
	{
		NIM_BOOL LOC9;
		LOC9 = 0;
		LOC9 = ((source ? source->Sup.len : 0) < ((NI) 1));
		if (LOC9) goto LA10;
		LOC9 = ((pattern ? pattern->Sup.len : 0) < ((NI) 1));
		LA10: ;
		if (!LOC9) goto LA11;
		nimln(64, "awknim.nim");
		result = ((NI) 0);
		goto BeforeRet;
	}
	LA11: ;
	memset((void*)(&found), 0, sizeof(found));
	nimln(66, "awknim.nim");
	LOC13 = 0;
	LOC13 = rawNewString(pattern->Sup.len + 4);
appendString(LOC13, ((NimStringDesc*) &TMP537));
appendString(LOC13, pattern);
	LOC14 = 0;
	LOC14 = re_143506(LOC13);
	chckNil((void*)(&found));
	memset((void*)(&found), 0, sizeof(found));
	find_143831(source, LOC14, ((NI) 0), ((NI) IL64(9223372036854775807)), (&found));
	nimln(67, "awknim.nim");
	{
		NIM_BOOL LOC17;
		Slice90081 j;
		Regexmatch141004 LOC20;
		Regexmatch141004 LOC21;
		Option141225 LOC22;
		Regexmatch141004 LOC23;
		Regexmatch141004 LOC24;
		NI TMP539;
		LOC17 = 0;
		LOC17 = issome_143693((&found));
		if (!LOC17) goto LA18;
		memset((void*)(&j), 0, sizeof(j));
		nimln(69, "awknim.nim");
		memset((void*)(&LOC20), 0, sizeof(LOC20));
		get_143701((&found), (&LOC20));
		memset((void*)(&LOC21), 0, sizeof(LOC21));
		capturebounds_141205((&LOC20), (&LOC21));
		LOC22 = HEX5BHEX5D_141213((&LOC21), ((NI) -1));
		j = get_141288((&LOC22));
		nimln(70, "awknim.nim");
		memset((void*)(&LOC23), 0, sizeof(LOC23));
		get_143701((&found), (&LOC23));
		memset((void*)(&LOC24), 0, sizeof(LOC24));
		captures_141209((&LOC23), (&LOC24));
		unsureAsgnRef((void**) (&(*dest)), HEX5BHEX5D_141272((&LOC24), ((NI) -1)));
		nimln(71, "awknim.nim");
		TMP539 = addInt(j.a, ((NI) 1));
		result = (NI)(TMP539);
		goto BeforeRet;
	}
	goto LA15;
	LA18: ;
	{
		nimln(73, "awknim.nim");
		result = ((NI) 0);
		goto BeforeRet;
	}
	LA15: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, HEX7E_145119)(NimStringDesc* source, NimStringDesc* pattern) {
	NIM_BOOL result;
	nimfr("~", "awknim.nim")
{	result = 0;
	nimln(131, "awknim.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((source ? source->Sup.len : 0) < ((NI) 1));
		if (!(LOC3)) goto LA4;
		LOC3 = ((pattern ? pattern->Sup.len : 0) < ((NI) 1));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(132, "awknim.nim");
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA5: ;
	nimln(133, "awknim.nim");
	{
		NIM_BOOL LOC9;
		LOC9 = 0;
		LOC9 = ((source ? source->Sup.len : 0) < ((NI) 1));
		if (LOC9) goto LA10;
		LOC9 = ((pattern ? pattern->Sup.len : 0) < ((NI) 1));
		LA10: ;
		if (!LOC9) goto LA11;
		nimln(134, "awknim.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA11: ;
	nimln(135, "awknim.nim");
	{
		NimStringDesc* LOC15;
		RegexHEX3Aobjecttype141019* LOC16;
		Option143524 LOC17;
		NIM_BOOL LOC18;
		LOC15 = 0;
		LOC15 = rawNewString(pattern->Sup.len + 4);
appendString(LOC15, ((NimStringDesc*) &TMP537));
appendString(LOC15, pattern);
		LOC16 = 0;
		LOC16 = re_143506(LOC15);
		memset((void*)(&LOC17), 0, sizeof(LOC17));
		find_143831(source, LOC16, ((NI) 0), ((NI) IL64(9223372036854775807)), (&LOC17));
		LOC18 = 0;
		LOC18 = issome_143693((&LOC17));
		if (!LOC18) goto LA19;
		nimln(136, "awknim.nim");
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA19: ;
	nimln(137, "awknim.nim");
	result = NIM_FALSE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, HEX21HEX7E_145134)(NimStringDesc* source, NimStringDesc* pattern) {
	NIM_BOOL result;
	nimfr("!~", "awknim.nim")
{	result = 0;
	nimln(140, "awknim.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((source ? source->Sup.len : 0) < ((NI) 1));
		if (!(LOC3)) goto LA4;
		LOC3 = ((pattern ? pattern->Sup.len : 0) < ((NI) 1));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(141, "awknim.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA5: ;
	nimln(142, "awknim.nim");
	{
		NIM_BOOL LOC9;
		LOC9 = 0;
		LOC9 = ((source ? source->Sup.len : 0) < ((NI) 1));
		if (LOC9) goto LA10;
		LOC9 = ((pattern ? pattern->Sup.len : 0) < ((NI) 1));
		LA10: ;
		if (!LOC9) goto LA11;
		nimln(143, "awknim.nim");
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA11: ;
	nimln(144, "awknim.nim");
	{
		NimStringDesc* LOC15;
		RegexHEX3Aobjecttype141019* LOC16;
		Option143524 LOC17;
		NIM_BOOL LOC18;
		LOC15 = 0;
		LOC15 = rawNewString(pattern->Sup.len + 4);
appendString(LOC15, ((NimStringDesc*) &TMP537));
appendString(LOC15, pattern);
		LOC16 = 0;
		LOC16 = re_143506(LOC15);
		memset((void*)(&LOC17), 0, sizeof(LOC17));
		find_143831(source, LOC16, ((NI) 0), ((NI) IL64(9223372036854775807)), (&LOC17));
		LOC18 = 0;
		LOC18 = issome_143693((&LOC17));
		if (!LOC18) goto LA19;
		nimln(145, "awknim.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA19: ;
	nimln(146, "awknim.nim");
	result = NIM_TRUE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, HEX3EHEX2A_145149)(NimStringDesc* text_145151, NimStringDesc* filename) {
	NIM_BOOL result;
	NimStringDesc* text;
	NimStringDesc* LOC1;
	nimfr(">*", "awknim.nim")
	result = 0;
	nimln(157, "awknim.nim");
	LOC1 = 0;
	LOC1 = rawNewString(text_145151->Sup.len + 1);
appendString(LOC1, text_145151);
appendString(LOC1, ((NimStringDesc*) &TMP540));
	text = LOC1;
	nimln(158, "awknim.nim");
	writefile_15469(filename, text);
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_19437;
	exchandler_19437 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_19437 = (*exchandler_19437).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_19436 = s;
}

static N_INLINE(NIM_BOOL, canbecycleroot_52058)(Cell47905* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(140, "gc.nim");
	nimln(1099, "system.nim");
	result = !((((*(*c).typ).flags &(1U<<((NU)(((NU8) 1))&7U)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_52820)(Cell47905* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(208, "gc.nim");
	{
		nimln(344, "system.nim");
		nimln(153, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(158, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(210, "gc.nim");
		incl_48647((&gch_50459.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_54419)(Cell47905* c) {
	nimfr("incRef", "gc.nim")
	nimln(235, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(238, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_52058(c);
		if (!LOC3) goto LA4;
		nimln(239, "gc.nim");
		rtladdcycleroot_52820(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(Cell47905*, usrtocell_52040)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(137, "gc.nim");
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_53601)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(218, "gc.nim");
	addzct_52017((&gch_50459.zct), c);
	popFrame();
}

static N_INLINE(void, decref_54001)(Cell47905* c) {
	nimfr("decRef", "gc.nim")
	nimln(225, "gc.nim");
	{
		nimln(186, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(187, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(226, "gc.nim");
		rtladdzct_53601(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(227, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_52058(c);
		if (!LOC6) goto LA7;
		nimln(230, "gc.nim");
		rtladdcycleroot_52820(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(263, "gc.nim");
	{
		Cell47905* LOC5;
		nimln(344, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(263, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_52040(src);
		incref_54419(LOC5);
	}
	LA3: ;
	nimln(264, "gc.nim");
	{
		Cell47905* LOC10;
		nimln(344, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(264, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_52040((*dest));
		decref_54001(LOC10);
	}
	LA8: ;
	nimln(265, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_19439), NIM_NIL);
}

N_NIMCALL(NIM_BOOL, HEX3EHEX3E_145155)(NimStringDesc* text_145157, NimStringDesc* filename) {
	NIM_BOOL result;
	NimStringDesc* text;
	NimStringDesc* LOC1;
	FILE* volatile fp;
	TSafePoint TMP541;
	nimfr(">>", "awknim.nim")
{	result = 0;
	nimln(167, "awknim.nim");
	LOC1 = 0;
	LOC1 = rawNewString(text_145157->Sup.len + 1);
appendString(LOC1, text_145157);
appendString(LOC1, ((NimStringDesc*) &TMP540));
	text = LOC1;
	fp = 0;
	nimln(170, "awknim.nim");
	pushSafePoint(&TMP541);
	TMP541.status = setjmp(TMP541.context);
	if (TMP541.status == 0) {
		nimln(171, "awknim.nim");
		fp = open_15417(filename, ((NU8) 4), ((NI) -1));
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
		{
			TMP541.status = 0;
			nimln(173, "awknim.nim");
			result = NIM_FALSE;
			popCurrentException();
			goto BeforeRet;
			popCurrentException();
		}
	}
	if (TMP541.status != 0) reraiseException();
	nimln(175, "awknim.nim");
	write_15489(fp, text);
	nimln(176, "awknim.nim");
	fflush(fp);
	nimln(177, "awknim.nim");
	fclose(fp);
	nimln(178, "awknim.nim");
	result = NIM_TRUE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, splitawkalt_145173)(NimStringDesc* source, TY15805** dest, NimStringDesc* match) {
	NI result;
	NimStringDesc* LOC1;
	RegexHEX3Aobjecttype141019* LOC2;
	nimfr("splitawkalt", "awknim.nim")
	result = 0;
	nimln(220, "awknim.nim");
	genericSeqAssign((&(*dest)), TMP542, (&NTI15805));
	nimln(221, "awknim.nim");
	LOC1 = 0;
	LOC1 = rawNewString(match->Sup.len + 4);
appendString(LOC1, ((NimStringDesc*) &TMP537));
appendString(LOC1, match);
	LOC2 = 0;
	LOC2 = re_143506(LOC1);
	unsureAsgnRef((void**) (&(*dest)), split_143894(source, LOC2, ((NI) -1), ((NI) 0)));
	nimln(222, "awknim.nim");
	result = ((*dest) ? (*dest)->Sup.len : 0);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, gsub_145202)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc** source) {
	NimStringDesc* result;
	NimStringDesc* LOC7;
	RegexHEX3Aobjecttype141019* LOC8;
	nimfr("gsub", "awknim.nim")
{	result = 0;
	nimln(245, "awknim.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((pattern ? pattern->Sup.len : 0) == ((NI) 0));
		if (LOC3) goto LA4;
		LOC3 = (((*source) ? (*source)->Sup.len : 0) == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(246, "awknim.nim");
		goto BeforeRet;
	}
	LA5: ;
	nimln(247, "awknim.nim");
	LOC7 = 0;
	LOC7 = rawNewString(pattern->Sup.len + 4);
appendString(LOC7, ((NimStringDesc*) &TMP537));
appendString(LOC7, pattern);
	LOC8 = 0;
	LOC8 = re_143506(LOC7);
	unsureAsgnRef((void**) (&(*source)), replace_144419((*source), LOC8, replacement));
	nimln(248, "awknim.nim");
	result = copyString((*source));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, gsub_145209)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc* source) {
	NimStringDesc* result;
	NimStringDesc* LOC7;
	RegexHEX3Aobjecttype141019* LOC8;
	nimfr("gsub", "awknim.nim")
{	result = 0;
	nimln(251, "awknim.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((pattern ? pattern->Sup.len : 0) == ((NI) 0));
		if (LOC3) goto LA4;
		LOC3 = ((source ? source->Sup.len : 0) == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(252, "awknim.nim");
		result = copyString(source);
		goto BeforeRet;
	}
	LA5: ;
	nimln(253, "awknim.nim");
	LOC7 = 0;
	LOC7 = rawNewString(pattern->Sup.len + 4);
appendString(LOC7, ((NimStringDesc*) &TMP537));
appendString(LOC7, pattern);
	LOC8 = 0;
	LOC8 = re_143506(LOC7);
	result = replace_144419(source, LOC8, replacement);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, patsplit_145215)(NimStringDesc* source, TY15805** field, NimStringDesc* pattern) {
	NI result;
	NI i;
	nimfr("patsplit", "awknim.nim")
	result = 0;
	nimln(291, "awknim.nim");
	genericSeqAssign((&(*field)), TMP542, (&NTI15805));
	nimln(292, "awknim.nim");
	i = ((NI) 0);
	{
		Regexmatch141004 found_145237;
		RegexHEX3Aobjecttype141019* HEX3Atmp_146418;
		NimStringDesc* LOC2;
		NIM_BOOL matchescrlf_146423;
		NIM_BOOL unicode_146425;
		unsigned long LOC3;
		NI strlen_146428;
		NI offset_146431;
		Option143524 match_146433;
		memset((void*)(&found_145237), 0, sizeof(found_145237));
		HEX3Atmp_146418 = 0;
		nimln(294, "awknim.nim");
		LOC2 = 0;
		LOC2 = rawNewString(pattern->Sup.len + 4);
appendString(LOC2, ((NimStringDesc*) &TMP537));
appendString(LOC2, pattern);
		HEX3Atmp_146418 = re_143506(LOC2);
		nimln(512, "nre.nim");
		matchescrlf_146423 = matchescrlf_141128(HEX3Atmp_146418);
		nimln(513, "nre.nim");
		nimln(352, "system.nim");
		nimln(513, "nre.nim");
		LOC3 = 0;
		LOC3 = getinfo_141133(HEX3Atmp_146418, ((int) 0));
		unicode_146425 = ((NU32)(((NU32) 0)) < (NU32)(((NU32) ((unsigned long)(LOC3 & ((NI) 2048))))));
		nimln(515, "nre.nim");
		{
			if (!NIM_TRUE) goto LA6;
			strlen_146428 = (source ? source->Sup.len : 0);
		}
		goto LA4;
		LA6: ;
		{
			strlen_146428 = ((NI) IL64(9223372036854775807));
		}
		LA4: ;
		nimln(517, "nre.nim");
		offset_146431 = ((NI) 0);
		memset((void*)(&match_146433), 0, sizeof(match_146433));
		{
			nimln(519, "nre.nim");
			while (1) {
				NI flags_146435;
				nimln(520, "nre.nim");
				flags_146435 = ((NI) 0);
				nimln(522, "nre.nim");
				{
					NIM_BOOL LOC13;
					Regexmatch141004 LOC15;
					Slice90081 LOC16;
					Regexmatch141004 LOC17;
					Slice90081 LOC18;
					LOC13 = 0;
					LOC13 = issome_143693((&match_146433));
					if (!(LOC13)) goto LA14;
					nimln(352, "system.nim");
					nimln(523, "nre.nim");
					memset((void*)(&LOC15), 0, sizeof(LOC15));
					get_143701((&match_146433), (&LOC15));
					LOC16 = matchbounds_141309((&LOC15));
					memset((void*)(&LOC17), 0, sizeof(LOC17));
					get_143701((&match_146433), (&LOC17));
					LOC18 = matchbounds_141309((&LOC17));
					LOC13 = (LOC16.b < LOC18.a);
					LA14: ;
					if (!LOC13) goto LA19;
					nimln(525, "nre.nim");
					flags_146435 = ((NI) 268435456);
				}
				LA19: ;
				nimln(527, "nre.nim");
				chckNil((void*)(&match_146433));
				memset((void*)(&match_146433), 0, sizeof(match_146433));
				matchimpl_143513(source, HEX3Atmp_146418, offset_146431, ((NI) IL64(9223372036854775807)), flags_146435, (&match_146433));
				nimln(529, "nre.nim");
				{
					NIM_BOOL LOC23;
					LOC23 = 0;
					LOC23 = isnone_143709((&match_146433));
					if (!LOC23) goto LA24;
					nimln(532, "nre.nim");
					{
						nimln(348, "system.nim");
						if (!(strlen_146428 <= offset_146431)) goto LA28;
						nimln(533, "nre.nim");
						goto LA9;
					}
					LA28: ;
					nimln(535, "nre.nim");
					{
						NIM_BOOL LOC32;
						NIM_BOOL LOC33;
						NIM_BOOL LOC34;
						NI TMP553;
						NI TMP554;
						NI TMP555;
						nimln(536, "nre.nim");
						LOC32 = 0;
						nimln(535, "nre.nim");
						LOC33 = 0;
						LOC34 = 0;
						LOC34 = matchescrlf_146423;
						if (!(LOC34)) goto LA35;
						TMP553 = subInt((source ? source->Sup.len : 0), ((NI) 1));
						LOC34 = (offset_146431 < (NI)(TMP553));
						LA35: ;
						LOC33 = LOC34;
						if (!(LOC33)) goto LA36;
						nimln(536, "nre.nim");
						if ((NU)(offset_146431) > (NU)(source->Sup.len)) raiseIndexError();
						LOC33 = ((NU8)(source->data[offset_146431]) == (NU8)(13));
						LA36: ;
						LOC32 = LOC33;
						if (!(LOC32)) goto LA37;
						TMP554 = addInt(offset_146431, ((NI) 1));
						if ((NU)((NI)(TMP554)) > (NU)(source->Sup.len)) raiseIndexError();
						LOC32 = ((NU8)(source->data[(NI)(TMP554)]) == (NU8)(10));
						LA37: ;
						if (!LOC32) goto LA38;
						nimln(538, "nre.nim");
						TMP555 = addInt(offset_146431, ((NI) 2));
						offset_146431 = (NI)(TMP555);
					}
					goto LA30;
					LA38: ;
					{
						NI LOC43;
						NI TMP556;
						if (!unicode_146425) goto LA41;
						nimln(541, "nre.nim");
						LOC43 = 0;
						LOC43 = runelenat_126392(source, ((NI)chckRange(offset_146431, ((NI) 0), ((NI) IL64(9223372036854775807)))));
						TMP556 = addInt(offset_146431, LOC43);
						offset_146431 = (NI)(TMP556);
						nimln(542, "nre.nim");
						{
							if (!!((offset_146431 <= strlen_146428))) goto LA46;
							failedassertimpl_90839(((NimStringDesc*) &TMP557));
						}
						LA46: ;
					}
					goto LA30;
					LA41: ;
					{
						NI TMP558;
						nimln(544, "nre.nim");
						TMP558 = addInt(offset_146431, ((NI) 1));
						offset_146431 = (NI)(TMP558);
					}
					LA30: ;
				}
				goto LA21;
				LA24: ;
				{
					Regexmatch141004 LOC50;
					Slice90081 LOC51;
					NI TMP559;
					nimln(546, "nre.nim");
					memset((void*)(&LOC50), 0, sizeof(LOC50));
					get_143701((&match_146433), (&LOC50));
					LOC51 = matchbounds_141309((&LOC50));
					TMP559 = addInt(LOC51.b, ((NI) 1));
					offset_146431 = (NI)(TMP559);
					nimln(548, "nre.nim");
					chckNil((void*)(&found_145237));
					memset((void*)(&found_145237), 0, sizeof(found_145237));
					get_143701((&match_146433), (&found_145237));
					nimln(295, "awknim.nim");
					{
						NimStringDesc* LOC54;
						NI TMP560;
						NimStringDesc* LOC57;
						nimln(352, "system.nim");
						nimln(295, "awknim.nim");
						LOC54 = 0;
						LOC54 = match_141305((&found_145237));
						if (!(((NI) 0) < (LOC54 ? LOC54->Sup.len : 0))) goto LA55;
						nimln(296, "awknim.nim");
						TMP560 = addInt(i, ((NI) 1));
						i = (NI)(TMP560);
						nimln(297, "awknim.nim");
						LOC57 = 0;
						LOC57 = match_141305((&found_145237));
						insert_145248(field, LOC57, ((NI)chckRange(i, ((NI) 0), ((NI) IL64(9223372036854775807)))));
					}
					LA55: ;
				}
				LA21: ;
			}
		} LA9: ;
	}
	nimln(299, "awknim.nim");
	{
		nimln(352, "system.nim");
		if (!(((NI) 0) < i)) goto LA60;
		nimln(300, "awknim.nim");
		delete_145804(field, ((NI) 0));
		nimln(301, "awknim.nim");
		result = i;
	}
	goto LA58;
	LA60: ;
	{
		nimln(303, "awknim.nim");
		result = ((NI) 0);
	}
	LA58: ;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47905* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(252, "gc.nim");
	c = usrtocell_52040(p);
	nimln(254, "gc.nim");
	{
		nimln(186, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(187, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(255, "gc.nim");
		rtladdzct_53601(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(NI, patsplit_146436)(NimStringDesc* source, TY15805** field, NimStringDesc* pattern, TY15805** sep) {
	NI result;
	NI i;
	NI s;
	NI e;
	NI c;
	Slice90081 j;
	nimfr("patsplit", "awknim.nim")
	result = 0;
	nimln(307, "awknim.nim");
	genericSeqAssign((&(*field)), TMP542, (&NTI15805));
	nimln(308, "awknim.nim");
	genericSeqAssign((&(*sep)), TMP542, (&NTI15805));
	nimln(309, "awknim.nim");
	i = ((NI) 0);
	s = ((NI) 0);
	e = ((NI) 0);
	c = ((NI) 0);
	memset((void*)(&j), 0, sizeof(j));
	{
		Regexmatch141004 found_146480;
		RegexHEX3Aobjecttype141019* HEX3Atmp_146576;
		NimStringDesc* LOC2;
		NIM_BOOL matchescrlf_146581;
		NIM_BOOL unicode_146583;
		unsigned long LOC3;
		NI strlen_146586;
		NI offset_146589;
		Option143524 match_146591;
		memset((void*)(&found_146480), 0, sizeof(found_146480));
		HEX3Atmp_146576 = 0;
		nimln(312, "awknim.nim");
		LOC2 = 0;
		LOC2 = rawNewString(pattern->Sup.len + 4);
appendString(LOC2, ((NimStringDesc*) &TMP537));
appendString(LOC2, pattern);
		HEX3Atmp_146576 = re_143506(LOC2);
		nimln(512, "nre.nim");
		matchescrlf_146581 = matchescrlf_141128(HEX3Atmp_146576);
		nimln(513, "nre.nim");
		nimln(352, "system.nim");
		nimln(513, "nre.nim");
		LOC3 = 0;
		LOC3 = getinfo_141133(HEX3Atmp_146576, ((int) 0));
		unicode_146583 = ((NU32)(((NU32) 0)) < (NU32)(((NU32) ((unsigned long)(LOC3 & ((NI) 2048))))));
		nimln(515, "nre.nim");
		{
			if (!NIM_TRUE) goto LA6;
			strlen_146586 = (source ? source->Sup.len : 0);
		}
		goto LA4;
		LA6: ;
		{
			strlen_146586 = ((NI) IL64(9223372036854775807));
		}
		LA4: ;
		nimln(517, "nre.nim");
		offset_146589 = ((NI) 0);
		memset((void*)(&match_146591), 0, sizeof(match_146591));
		{
			nimln(519, "nre.nim");
			while (1) {
				NI flags_146593;
				nimln(520, "nre.nim");
				flags_146593 = ((NI) 0);
				nimln(522, "nre.nim");
				{
					NIM_BOOL LOC13;
					Regexmatch141004 LOC15;
					Slice90081 LOC16;
					Regexmatch141004 LOC17;
					Slice90081 LOC18;
					LOC13 = 0;
					LOC13 = issome_143693((&match_146591));
					if (!(LOC13)) goto LA14;
					nimln(352, "system.nim");
					nimln(523, "nre.nim");
					memset((void*)(&LOC15), 0, sizeof(LOC15));
					get_143701((&match_146591), (&LOC15));
					LOC16 = matchbounds_141309((&LOC15));
					memset((void*)(&LOC17), 0, sizeof(LOC17));
					get_143701((&match_146591), (&LOC17));
					LOC18 = matchbounds_141309((&LOC17));
					LOC13 = (LOC16.b < LOC18.a);
					LA14: ;
					if (!LOC13) goto LA19;
					nimln(525, "nre.nim");
					flags_146593 = ((NI) 268435456);
				}
				LA19: ;
				nimln(527, "nre.nim");
				chckNil((void*)(&match_146591));
				memset((void*)(&match_146591), 0, sizeof(match_146591));
				matchimpl_143513(source, HEX3Atmp_146576, offset_146589, ((NI) IL64(9223372036854775807)), flags_146593, (&match_146591));
				nimln(529, "nre.nim");
				{
					NIM_BOOL LOC23;
					LOC23 = 0;
					LOC23 = isnone_143709((&match_146591));
					if (!LOC23) goto LA24;
					nimln(532, "nre.nim");
					{
						nimln(348, "system.nim");
						if (!(strlen_146586 <= offset_146589)) goto LA28;
						nimln(533, "nre.nim");
						goto LA9;
					}
					LA28: ;
					nimln(535, "nre.nim");
					{
						NIM_BOOL LOC32;
						NIM_BOOL LOC33;
						NIM_BOOL LOC34;
						NI TMP561;
						NI TMP562;
						NI TMP563;
						nimln(536, "nre.nim");
						LOC32 = 0;
						nimln(535, "nre.nim");
						LOC33 = 0;
						LOC34 = 0;
						LOC34 = matchescrlf_146581;
						if (!(LOC34)) goto LA35;
						TMP561 = subInt((source ? source->Sup.len : 0), ((NI) 1));
						LOC34 = (offset_146589 < (NI)(TMP561));
						LA35: ;
						LOC33 = LOC34;
						if (!(LOC33)) goto LA36;
						nimln(536, "nre.nim");
						if ((NU)(offset_146589) > (NU)(source->Sup.len)) raiseIndexError();
						LOC33 = ((NU8)(source->data[offset_146589]) == (NU8)(13));
						LA36: ;
						LOC32 = LOC33;
						if (!(LOC32)) goto LA37;
						TMP562 = addInt(offset_146589, ((NI) 1));
						if ((NU)((NI)(TMP562)) > (NU)(source->Sup.len)) raiseIndexError();
						LOC32 = ((NU8)(source->data[(NI)(TMP562)]) == (NU8)(10));
						LA37: ;
						if (!LOC32) goto LA38;
						nimln(538, "nre.nim");
						TMP563 = addInt(offset_146589, ((NI) 2));
						offset_146589 = (NI)(TMP563);
					}
					goto LA30;
					LA38: ;
					{
						NI LOC43;
						NI TMP564;
						if (!unicode_146583) goto LA41;
						nimln(541, "nre.nim");
						LOC43 = 0;
						LOC43 = runelenat_126392(source, ((NI)chckRange(offset_146589, ((NI) 0), ((NI) IL64(9223372036854775807)))));
						TMP564 = addInt(offset_146589, LOC43);
						offset_146589 = (NI)(TMP564);
						nimln(542, "nre.nim");
						{
							if (!!((offset_146589 <= strlen_146586))) goto LA46;
							failedassertimpl_90839(((NimStringDesc*) &TMP557));
						}
						LA46: ;
					}
					goto LA30;
					LA41: ;
					{
						NI TMP565;
						nimln(544, "nre.nim");
						TMP565 = addInt(offset_146589, ((NI) 1));
						offset_146589 = (NI)(TMP565);
					}
					LA30: ;
				}
				goto LA21;
				LA24: ;
				{
					Regexmatch141004 LOC50;
					Slice90081 LOC51;
					NI TMP566;
					nimln(546, "nre.nim");
					memset((void*)(&LOC50), 0, sizeof(LOC50));
					get_143701((&match_146591), (&LOC50));
					LOC51 = matchbounds_141309((&LOC50));
					TMP566 = addInt(LOC51.b, ((NI) 1));
					offset_146589 = (NI)(TMP566);
					nimln(548, "nre.nim");
					chckNil((void*)(&found_146480));
					memset((void*)(&found_146480), 0, sizeof(found_146480));
					get_143701((&match_146591), (&found_146480));
					nimln(313, "awknim.nim");
					{
						NimStringDesc* LOC54;
						NI TMP567;
						NimStringDesc* LOC57;
						Regexmatch141004 LOC58;
						Option141225 LOC59;
						NimStringDesc* LOC65;
						nimln(352, "system.nim");
						nimln(313, "awknim.nim");
						LOC54 = 0;
						LOC54 = match_141305((&found_146480));
						if (!(((NI) 0) < (LOC54 ? LOC54->Sup.len : 0))) goto LA55;
						nimln(314, "awknim.nim");
						TMP567 = addInt(i, ((NI) 1));
						i = (NI)(TMP567);
						nimln(315, "awknim.nim");
						LOC57 = 0;
						LOC57 = match_141305((&found_146480));
						insert_145248(field, LOC57, ((NI)chckRange(i, ((NI) 0), ((NI) IL64(9223372036854775807)))));
						nimln(316, "awknim.nim");
						memset((void*)(&LOC58), 0, sizeof(LOC58));
						capturebounds_141205((&found_146480), (&LOC58));
						LOC59 = HEX5BHEX5D_141213((&LOC58), ((NI) -1));
						j = get_141288((&LOC59));
						nimln(317, "awknim.nim");
						{
							NI TMP568;
							if (!(i == ((NI) 1))) goto LA62;
							nimln(318, "awknim.nim");
							s = ((NI) 0);
							nimln(319, "awknim.nim");
							TMP568 = subInt(j.a, ((NI) 1));
							e = (NI)(TMP568);
							nimln(320, "awknim.nim");
							c = j.b;
						}
						goto LA60;
						LA62: ;
						{
							NI TMP569;
							NI TMP570;
							nimln(322, "awknim.nim");
							TMP569 = addInt(c, ((NI) 1));
							s = (NI)(TMP569);
							nimln(323, "awknim.nim");
							TMP570 = subInt(j.a, ((NI) 1));
							e = (NI)(TMP570);
							nimln(324, "awknim.nim");
							c = j.b;
						}
						LA60: ;
						nimln(325, "awknim.nim");
						LOC65 = 0;
						LOC65 = copyStrLast(source, s, e);
						insert_145248(sep, LOC65, ((NI)chckRange(i, ((NI) 0), ((NI) IL64(9223372036854775807)))));
					}
					LA55: ;
				}
				LA21: ;
			}
		} LA9: ;
	}
	nimln(327, "awknim.nim");
	{
		NIM_BOOL LOC68;
		NIM_BOOL LOC70;
		NI TMP571;
		NimStringDesc* LOC74;
		NimStringDesc* LOC75;
		LOC68 = 0;
		nimln(352, "system.nim");
		LOC68 = (((NI) 0) < c);
		if (LOC68) goto LA69;
		nimln(327, "awknim.nim");
		LOC70 = 0;
		LOC70 = (c == ((NI) 0));
		if (!(LOC70)) goto LA71;
		LOC70 = (i == ((NI) 1));
		LA71: ;
		LOC68 = LOC70;
		LA69: ;
		if (!LOC68) goto LA72;
		nimln(328, "awknim.nim");
		TMP571 = addInt(j.b, ((NI) 1));
		LOC74 = 0;
		LOC74 = copyStrLast(source, (NI)(TMP571), (source ? source->Sup.len : 0));
		(*sep) = (TY15805*) incrSeqV2(&((*sep))->Sup, sizeof(NimStringDesc*));
		LOC75 = 0;
		LOC75 = (*sep)->data[(*sep)->Sup.len]; (*sep)->data[(*sep)->Sup.len] = copyStringRC1(LOC74);
		if (LOC75) nimGCunrefNoCycle(LOC75);
		++(*sep)->Sup.len;
	}
	LA72: ;
	nimln(330, "awknim.nim");
	{
		nimln(352, "system.nim");
		if (!(((NI) 0) < i)) goto LA78;
		nimln(331, "awknim.nim");
		delete_145804(field, ((NI) 0));
		nimln(332, "awknim.nim");
		delete_145804(sep, ((NI) 0));
		nimln(333, "awknim.nim");
		result = i;
	}
	goto LA76;
	LA78: ;
	{
		nimln(335, "awknim.nim");
		insert_145248(field, source, ((NI) 1));
		nimln(336, "awknim.nim");
		delete_145804(field, ((NI) 0));
		nimln(337, "awknim.nim");
		result = ((NI) 0);
	}
	LA76: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, unpatsplit_146594)(TY15805* field, TY15805* sep) {
	NimStringDesc* result;
	NimStringDesc* o;
	nimfr("unpatsplit", "awknim.nim")
{	result = 0;
	nimln(352, "awknim.nim");
	o = copyString(((NimStringDesc*) &TMP543));
	nimln(353, "awknim.nim");
	{
		nimln(352, "system.nim");
		nimln(353, "awknim.nim");
		if (!((sep ? sep->Sup.len : 0) < (field ? field->Sup.len : 0))) goto LA3;
		nimln(354, "awknim.nim");
		result = copyString(o);
		goto BeforeRet;
	}
	LA3: ;
	{
		NI c_146634;
		NI HEX3Atmp_146652;
		NI TMP572;
		NI res_146655;
		c_146634 = 0;
		HEX3Atmp_146652 = 0;
		nimln(355, "awknim.nim");
		TMP572 = subInt((field ? field->Sup.len : 0), ((NI) 1));
		HEX3Atmp_146652 = (NI)(TMP572);
		nimln(1873, "system.nim");
		res_146655 = ((NI) 0);
		{
			nimln(1874, "system.nim");
			while (1) {
				NI TMP573;
				if (!(res_146655 <= HEX3Atmp_146652)) goto LA7;
				nimln(1875, "system.nim");
				c_146634 = res_146655;
				nimln(356, "awknim.nim");
				{
					NimStringDesc* LOC12;
					nimln(352, "system.nim");
					nimln(356, "awknim.nim");
					if ((NU)(c_146634) >= (NU)(field->Sup.len)) raiseIndexError();
					if (!(((NI) 0) < (field->data[c_146634] ? field->data[c_146634]->Sup.len : 0))) goto LA10;
					nimln(357, "awknim.nim");
					LOC12 = 0;
					if ((NU)(c_146634) >= (NU)(sep->Sup.len)) raiseIndexError();
					if ((NU)(c_146634) >= (NU)(field->Sup.len)) raiseIndexError();
					LOC12 = rawNewString(o->Sup.len + sep->data[c_146634]->Sup.len + field->data[c_146634]->Sup.len + 0);
appendString(LOC12, o);
appendString(LOC12, sep->data[c_146634]);
appendString(LOC12, field->data[c_146634]);
					o = LOC12;
				}
				LA10: ;
				nimln(1894, "system.nim");
				TMP573 = addInt(res_146655, ((NI) 1));
				res_146655 = (NI)(TMP573);
			} LA7: ;
		}
	}
	nimln(358, "awknim.nim");
	{
		NI TMP574;
		NimStringDesc* LOC17;
		NI TMP575;
		nimln(352, "system.nim");
		nimln(358, "awknim.nim");
		TMP574 = subInt((sep ? sep->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TMP574)) >= (NU)(sep->Sup.len)) raiseIndexError();
		if (!(((NI) 0) < (sep->data[(NI)(TMP574)] ? sep->data[(NI)(TMP574)]->Sup.len : 0))) goto LA15;
		nimln(359, "awknim.nim");
		LOC17 = 0;
		TMP575 = subInt((sep ? sep->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TMP575)) >= (NU)(sep->Sup.len)) raiseIndexError();
		LOC17 = rawNewString(o->Sup.len + sep->data[(NI)(TMP575)]->Sup.len + 0);
appendString(LOC17, o);
appendString(LOC17, sep->data[(NI)(TMP575)]);
		o = LOC17;
	}
	LA15: ;
	nimln(360, "awknim.nim");
	result = copyString(o);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, sub_146659)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc** source) {
	NimStringDesc* result;
	TY15805* field;
	TY15805* sep;
	nimfr("sub", "awknim.nim")
{	result = 0;
	nimln(383, "awknim.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((pattern ? pattern->Sup.len : 0) == ((NI) 0));
		if (LOC3) goto LA4;
		LOC3 = (((*source) ? (*source)->Sup.len : 0) == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(384, "awknim.nim");
		result = copyString((*source));
		goto BeforeRet;
	}
	LA5: ;
	nimln(385, "awknim.nim");
	field = newseq_146679(((NI) 0));
	sep = newseq_146679(((NI) 0));
	nimln(386, "awknim.nim");
	{
		NI LOC9;
		NimStringDesc* LOC12;
		nimln(352, "system.nim");
		nimln(386, "awknim.nim");
		LOC9 = 0;
		LOC9 = patsplit_146436((*source), (&field), pattern, (&sep));
		if (!(((NI) 0) < LOC9)) goto LA10;
		nimln(387, "awknim.nim");
		if ((NU)(((NI) 0)) >= (NU)(field->Sup.len)) raiseIndexError();
		LOC12 = 0;
		LOC12 = field->data[((NI) 0)]; field->data[((NI) 0)] = copyStringRC1(replacement);
		if (LOC12) nimGCunrefNoCycle(LOC12);
		nimln(388, "awknim.nim");
		unsureAsgnRef((void**) (&(*source)), unpatsplit_146594(field, sep));
	}
	LA10: ;
	nimln(389, "awknim.nim");
	result = copyString((*source));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, sub_146708)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc* source) {
	NimStringDesc* result;
	TY15805* field;
	TY15805* sep;
	nimfr("sub", "awknim.nim")
{	result = 0;
	nimln(392, "awknim.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((pattern ? pattern->Sup.len : 0) == ((NI) 0));
		if (LOC3) goto LA4;
		LOC3 = ((source ? source->Sup.len : 0) == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(393, "awknim.nim");
		result = copyString(source);
		goto BeforeRet;
	}
	LA5: ;
	nimln(394, "awknim.nim");
	field = newseq_146679(((NI) 0));
	sep = newseq_146679(((NI) 0));
	nimln(395, "awknim.nim");
	{
		NI LOC9;
		NimStringDesc* LOC12;
		nimln(352, "system.nim");
		nimln(395, "awknim.nim");
		LOC9 = 0;
		LOC9 = patsplit_146436(source, (&field), pattern, (&sep));
		if (!(((NI) 0) < LOC9)) goto LA10;
		nimln(396, "awknim.nim");
		if ((NU)(((NI) 0)) >= (NU)(field->Sup.len)) raiseIndexError();
		LOC12 = 0;
		LOC12 = field->data[((NI) 0)]; field->data[((NI) 0)] = copyStringRC1(replacement);
		if (LOC12) nimGCunrefNoCycle(LOC12);
		nimln(397, "awknim.nim");
		result = unpatsplit_146594(field, sep);
		goto BeforeRet;
	}
	LA10: ;
	nimln(398, "awknim.nim");
	result = copyString(source);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, sub_146746)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc** source, NI occurance) {
	NimStringDesc* result;
	TY15805* field;
	TY15805* sep;
	NI p;
	nimfr("sub", "awknim.nim")
{	result = 0;
	nimln(401, "awknim.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((pattern ? pattern->Sup.len : 0) == ((NI) 0));
		if (LOC3) goto LA4;
		LOC3 = (((*source) ? (*source)->Sup.len : 0) == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(402, "awknim.nim");
		result = copyString((*source));
		goto BeforeRet;
	}
	LA5: ;
	nimln(403, "awknim.nim");
	field = newseq_146679(((NI) 0));
	sep = newseq_146679(((NI) 0));
	nimln(404, "awknim.nim");
	p = patsplit_146436((*source), (&field), pattern, (&sep));
	nimln(405, "awknim.nim");
	{
		nimln(352, "system.nim");
		if (!(((NI) 0) < p)) goto LA9;
		nimln(406, "awknim.nim");
		{
			NI TMP576;
			NimStringDesc* LOC15;
			if (!(occurance <= p)) goto LA13;
			nimln(407, "awknim.nim");
			TMP576 = subInt(occurance, ((NI) 1));
			if ((NU)((NI)(TMP576)) >= (NU)(field->Sup.len)) raiseIndexError();
			LOC15 = 0;
			LOC15 = field->data[(NI)(TMP576)]; field->data[(NI)(TMP576)] = copyStringRC1(replacement);
			if (LOC15) nimGCunrefNoCycle(LOC15);
			nimln(408, "awknim.nim");
			unsureAsgnRef((void**) (&(*source)), unpatsplit_146594(field, sep));
		}
		LA13: ;
	}
	LA9: ;
	nimln(409, "awknim.nim");
	result = copyString((*source));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, sub_146787)(NimStringDesc* pattern, NimStringDesc* replacement, NimStringDesc* source, NI occurance) {
	NimStringDesc* result;
	TY15805* field;
	TY15805* sep;
	NI p;
	nimfr("sub", "awknim.nim")
{	result = 0;
	nimln(412, "awknim.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((pattern ? pattern->Sup.len : 0) == ((NI) 0));
		if (LOC3) goto LA4;
		LOC3 = ((source ? source->Sup.len : 0) == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(413, "awknim.nim");
		result = copyString(source);
		goto BeforeRet;
	}
	LA5: ;
	nimln(414, "awknim.nim");
	field = newseq_146679(((NI) 0));
	sep = newseq_146679(((NI) 0));
	nimln(415, "awknim.nim");
	p = patsplit_146436(source, (&field), pattern, (&sep));
	nimln(416, "awknim.nim");
	{
		nimln(352, "system.nim");
		if (!(((NI) 0) < p)) goto LA9;
		nimln(417, "awknim.nim");
		{
			NI TMP577;
			NimStringDesc* LOC15;
			if (!(occurance <= p)) goto LA13;
			nimln(418, "awknim.nim");
			TMP577 = subInt(occurance, ((NI) 1));
			if ((NU)((NI)(TMP577)) >= (NU)(field->Sup.len)) raiseIndexError();
			LOC15 = 0;
			LOC15 = field->data[(NI)(TMP577)]; field->data[(NI)(TMP577)] = copyStringRC1(replacement);
			if (LOC15) nimGCunrefNoCycle(LOC15);
			nimln(419, "awknim.nim");
			result = unpatsplit_146594(field, sep);
			goto BeforeRet;
		}
		LA13: ;
	}
	LA9: ;
	nimln(420, "awknim.nim");
	result = copyString(source);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, index_146827)(NimStringDesc* source, NimStringDesc* target) {
	NI result;
	nimfr("index", "awknim.nim")
{	result = 0;
	nimln(438, "awknim.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((source ? source->Sup.len : 0) == ((NI) 0));
		if (LOC3) goto LA4;
		LOC3 = ((target ? target->Sup.len : 0) == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(439, "awknim.nim");
		result = ((NI) -1);
		goto BeforeRet;
	}
	LA5: ;
	nimln(440, "awknim.nim");
	result = nsuFindStr(source, target, ((NI) 0));
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, substrawk_146832)(NimStringDesc* source, NI* a, NI aLen0) {
	NimStringDesc* result;
	NI length;
	NI start;
	NI alen;
	NimStringDesc* newsource;
	NimStringDesc* final;
	nimfr("substrawk", "awknim.nim")
{	result = 0;
	nimln(461, "awknim.nim");
	length = ((NI) -1);
	start = ((NI) -1);
	nimln(462, "awknim.nim");
	alen = aLen0;
	nimln(464, "awknim.nim");
	{
		if (!(alen < ((NI) 1))) goto LA3;
		nimln(465, "awknim.nim");
		result = copyString(((NimStringDesc*) &TMP543));
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		nimln(466, "awknim.nim");
		if (!(alen == ((NI) 1))) goto LA6;
		nimln(467, "awknim.nim");
		if ((NU)(((NI) 0)) >= (NU)(aLen0)) raiseIndexError();
		start = a[((NI) 0)];
		nimln(468, "awknim.nim");
		length = alen;
	}
	goto LA1;
	LA6: ;
	{
		nimln(469, "awknim.nim");
		if (!(alen == ((NI) 2))) goto LA9;
		nimln(470, "awknim.nim");
		if ((NU)(((NI) 0)) >= (NU)(aLen0)) raiseIndexError();
		start = a[((NI) 0)];
		nimln(471, "awknim.nim");
		if ((NU)(((NI) 1)) >= (NU)(aLen0)) raiseIndexError();
		length = a[((NI) 1)];
	}
	goto LA1;
	LA9: ;
	LA1: ;
	nimln(473, "awknim.nim");
	{
		nimln(352, "system.nim");
		nimln(473, "awknim.nim");
		if (!((source ? source->Sup.len : 0) < length)) goto LA13;
		nimln(474, "awknim.nim");
		length = (source ? source->Sup.len : 0);
	}
	LA13: ;
	nimln(475, "awknim.nim");
	{
		if (!(start < ((NI) 0))) goto LA17;
		nimln(476, "awknim.nim");
		start = ((NI) 0);
	}
	LA17: ;
	nimln(477, "awknim.nim");
	{
		NIM_BOOL LOC21;
		NIM_BOOL LOC22;
		LOC21 = 0;
		LOC22 = 0;
		nimln(352, "system.nim");
		nimln(477, "awknim.nim");
		LOC22 = ((source ? source->Sup.len : 0) < start);
		if (LOC22) goto LA23;
		LOC22 = (length < ((NI) 1));
		LA23: ;
		LOC21 = LOC22;
		if (LOC21) goto LA24;
		LOC21 = ((source ? source->Sup.len : 0) < ((NI) 1));
		LA24: ;
		if (!LOC21) goto LA25;
		nimln(478, "awknim.nim");
		result = copyString(((NimStringDesc*) &TMP543));
		goto BeforeRet;
	}
	LA25: ;
	nimln(480, "awknim.nim");
	newsource = copyString(source);
	nimln(481, "awknim.nim");
	final = copyString(((NimStringDesc*) &TMP543));
	{
		NI i_146859;
		NI HEX3Atmp_146861;
		NI TMP578;
		NI res_146864;
		i_146859 = 0;
		HEX3Atmp_146861 = 0;
		nimln(482, "awknim.nim");
		TMP578 = subInt((source ? source->Sup.len : 0), ((NI) 1));
		HEX3Atmp_146861 = (NI)(TMP578);
		nimln(1873, "system.nim");
		res_146864 = ((NI) 0);
		{
			nimln(1874, "system.nim");
			while (1) {
				NI TMP580;
				if (!(res_146864 <= HEX3Atmp_146861)) goto LA29;
				nimln(1875, "system.nim");
				i_146859 = res_146864;
				nimln(483, "awknim.nim");
				{
					NIM_BOOL LOC32;
					NI TMP579;
					LOC32 = 0;
					nimln(348, "system.nim");
					LOC32 = (start <= i_146859);
					if (!(LOC32)) goto LA33;
					nimln(483, "awknim.nim");
					TMP579 = addInt(start, length);
					LOC32 = (i_146859 < (NI)(TMP579));
					LA33: ;
					if (!LOC32) goto LA34;
					nimln(484, "awknim.nim");
					if ((NU)(i_146859) > (NU)(newsource->Sup.len)) raiseIndexError();
					final = addChar(final, newsource->data[i_146859]);
				}
				LA34: ;
				nimln(1894, "system.nim");
				TMP580 = addInt(res_146864, ((NI) 1));
				res_146864 = (NI)(TMP580);
			} LA29: ;
		}
	}
	nimln(485, "awknim.nim");
	{
		nimln(352, "system.nim");
		nimln(485, "awknim.nim");
		if (!(((NI) 0) < (final ? final->Sup.len : 0))) goto LA38;
		nimln(486, "awknim.nim");
		result = copyString(final);
		goto BeforeRet;
	}
	goto LA36;
	LA38: ;
	{
		nimln(488, "awknim.nim");
		result = copyString(((NimStringDesc*) &TMP543));
		goto BeforeRet;
	}
	LA36: ;
	}BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_awknimInit000)(void) {
	nimfr("awknim", "awknim.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_awknimDatInit000)(void) {
}

