/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/adminuser/Nim/lib -o /home/adminuser/awknim/nimcache/stdlib_etcpriv.o /home/adminuser/awknim/nimcache/stdlib_etcpriv.c */
#define NIM_INTBITS 64

#include "nimbase.h"
static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_104004)(NCSTRING cs, NI i);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* frameptr_19436;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_104004)(NCSTRING cs, NI i) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NI TMP158;
	NI TMP159;
	nimfr("isMagicIdentSeparatorRune", "etcpriv.nim")
	result = 0;
	nimln(21, "etcpriv.nim");
	nimln(22, "etcpriv.nim");
	LOC1 = 0;
	nimln(21, "etcpriv.nim");
	LOC2 = 0;
	LOC2 = ((NU8)(cs[i]) == (NU8)(226));
	if (!(LOC2)) goto LA3;
	nimln(22, "etcpriv.nim");
	TMP158 = addInt(i, ((NI) 1));
	LOC2 = ((NU8)(cs[(NI)(TMP158)]) == (NU8)(128));
	LA3: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA4;
	nimln(23, "etcpriv.nim");
	TMP159 = addInt(i, ((NI) 2));
	LOC1 = ((NU8)(cs[(NI)(TMP159)]) == (NU8)(147));
	LA4: ;
	result = LOC1;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void) {
	nimfr("etcpriv", "etcpriv.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void) {
}

