/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/adminuser/Nim/lib -o /home/adminuser/awknim/nimcache/stdlib_util.o /home/adminuser/awknim/nimcache/stdlib_util.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Valueerror3446 Valueerror3446;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47905 Cell47905;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Gcheap50418 Gcheap50418;
typedef struct Gcstack50416 Gcstack50416;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50414 Gcstat50414;
typedef struct Table141032 Table141032;
typedef struct Keyvaluepairseq141035 Keyvaluepairseq141035;
typedef struct Keyerror3448 Keyerror3448;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
typedef struct Keyvaluepair141038 Keyvaluepair141038;
typedef NU8 TY82010[32];
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3446  {
  Exception Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30088  {
NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50418  {
Gcstack50416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50414 stat;
};
struct  Table141032  {
Keyvaluepairseq141035* data;
NI counter;
};
struct  Keyerror3448  {
  Valueerror3446 Sup;
};
struct  Gcstack50416  {
Gcstack50416* prev;
Gcstack50416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30019[8];
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {
NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {
TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct Keyvaluepair141038 {
NI Field0;
NimStringDesc* Field1;
NI Field2;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
struct Keyvaluepairseq141035 {
  TGenericSeq Sup;
  Keyvaluepair141038 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, checknil_122032)(NimStringDesc* arg);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell47905*, usrtocell_52040)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_53601)(Cell47905* c);
N_NOINLINE(void, addzct_52017)(Cellseq47921* s, Cell47905* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NIM_BOOL, haskey_141346)(Table141032 t, NimStringDesc* key);
N_NIMCALL(NI, HEX5BHEX5D_141378)(Table141032 t, NimStringDesc* key);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
NIM_CONST TY82010 Ident_122016 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03,
0xFE, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
NIM_CONST TY82010 Startident_122018 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0xFE, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
STRING_LITERAL(TMP325, "Cannot use nil capture", 22);
STRING_LITERAL(TMP353, "Key does not exist in table: ", 29);
extern TNimType NTI24025; /* ref ValueError */
extern TNimType NTI3446; /* ValueError */
extern TFrame* frameptr_19436;
extern Gcheap50418 gch_50459;
extern TNimType NTI141604; /* ref KeyError */
extern TNimType NTI3448; /* KeyError */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(Cell47905*, usrtocell_52040)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(137, "gc.nim");
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_53601)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(218, "gc.nim");
	addzct_52017((&gch_50459.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47905* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(252, "gc.nim");
	c = usrtocell_52040(p);
	nimln(254, "gc.nim");
	{
		nimln(186, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(187, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(255, "gc.nim");
		rtladdzct_53601(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, checknil_122032)(NimStringDesc* arg) {
	NimStringDesc* result;
	nimfr("checkNil", "util.nim")
{	result = 0;
	nimln(14, "util.nim");
	{
		Valueerror3446* e_122039;
		NimStringDesc* LOC5;
		if (!(arg == NIM_NIL)) goto LA3;
		e_122039 = 0;
		nimln(2509, "system.nim");
		e_122039 = (Valueerror3446*) newObj((&NTI24025), sizeof(Valueerror3446));
		(*e_122039).Sup.Sup.m_type = (&NTI3446);
		nimln(2510, "system.nim");
		LOC5 = 0;
		LOC5 = (*e_122039).Sup.message; (*e_122039).Sup.message = copyStringRC1(((NimStringDesc*) &TMP325));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(15, "util.nim");
		raiseException((Exception*)e_122039, "ValueError");
	}
	goto LA1;
	LA3: ;
	{
		nimln(17, "util.nim");
		result = copyString(arg);
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(270, "gc.nim");
	{
		Cell47905* c;
		nimln(344, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(271, "gc.nim");
		c = usrtocell_52040(src);
		nimln(188, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(273, "gc.nim");
	{
		Cell47905* c;
		nimln(344, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(274, "gc.nim");
		c = usrtocell_52040((*dest));
		nimln(275, "gc.nim");
		{
			nimln(186, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(187, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(276, "gc.nim");
			rtladdzct_53601(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(277, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, fget_141335)(Table141032 self, NimStringDesc* key) {
	NI result;
	nimfr("fget", "util.nim")
{	result = 0;
	nimln(5, "util.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = haskey_141346(self, key);
		if (!LOC3) goto LA4;
		nimln(6, "util.nim");
		result = HEX5BHEX5D_141378(self, key);
		goto BeforeRet;
	}
	goto LA1;
	LA4: ;
	{
		Keyerror3448* e_141617;
		NimStringDesc* LOC7;
		e_141617 = 0;
		nimln(2509, "system.nim");
		e_141617 = (Keyerror3448*) newObj((&NTI141604), sizeof(Keyerror3448));
		(*e_141617).Sup.Sup.Sup.m_type = (&NTI3448);
		nimln(2510, "system.nim");
		nimln(8, "util.nim");
		LOC7 = 0;
		LOC7 = rawNewString(key->Sup.len + 29);
appendString(LOC7, ((NimStringDesc*) &TMP353));
appendString(LOC7, key);
		asgnRefNoCycle((void**) (&(*e_141617).Sup.Sup.message), LOC7);
		raiseException((Exception*)e_141617, "KeyError");
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_utilInit000)(void) {
	nimfr("util", "util.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_utilDatInit000)(void) {
}

