/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/adminuser/Nim/lib -o /home/adminuser/awknim/nimcache/stdlib_tables.o /home/adminuser/awknim/nimcache/stdlib_tables.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Keyvaluepair141038 Keyvaluepair141038;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Keyvaluepairseq141035 Keyvaluepairseq141035;
typedef struct Table141032 Table141032;
typedef struct Keyerror3448 Keyerror3448;
typedef struct Valueerror3446 Valueerror3446;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct Cell47905 Cell47905;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Gcheap50418 Gcheap50418;
typedef struct Gcstack50416 Gcstack50416;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50414 Gcstat50414;
typedef struct Table141657 Table141657;
typedef struct Keyvaluepairseq141660 Keyvaluepairseq141660;
typedef struct Keyvaluepair141663 Keyvaluepair141663;
typedef struct Table142087 Table142087;
typedef struct Keyvaluepairseq142090 Keyvaluepairseq142090;
typedef struct Keyvaluepair142093 Keyvaluepair142093;
typedef struct Option141225 Option141225;
typedef struct Slice90081 Slice90081;
typedef struct TY142743 TY142743;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Keyvaluepair141038 {
NI Field0;
NimStringDesc* Field1;
NI Field2;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Table141032  {
Keyvaluepairseq141035* data;
NI counter;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3446  {
  Exception Sup;
};
struct  Keyerror3448  {
  Valueerror3446 Sup;
};
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30088  {
NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50418  {
Gcstack50416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50414 stat;
};
struct  Table141657  {
Keyvaluepairseq141660* data;
NI counter;
};
struct Keyvaluepair141663 {
NI Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct  Table142087  {
Keyvaluepairseq142090* data;
NI counter;
};
struct  Slice90081  {
NI a;
NI b;
};
struct  Option141225  {
Slice90081 val;
NIM_BOOL has;
};
struct Keyvaluepair142093 {
NI Field0;
NimStringDesc* Field1;
Option141225 Field2;
};
struct TY142743 {
NimStringDesc* Field0;
NI Field1;
};
struct  Gcstack50416  {
Gcstack50416* prev;
Gcstack50416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30019[8];
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {
NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {
TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
struct Keyvaluepairseq141035 {
  TGenericSeq Sup;
  Keyvaluepair141038 data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq141660 {
  TGenericSeq Sup;
  Keyvaluepair141663 data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq142090 {
  TGenericSeq Sup;
  Keyvaluepair142093 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isempty_118259)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isfilled_118263)(NI hcode);
static N_INLINE(NIM_BOOL, mustrehash_118268)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_90839)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nexttry_118401)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, rightsize_118532)(NI count);
N_NIMCALL(NI, nextpoweroftwo_114229)(NI x);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP341)(void* p, NI op);
static N_INLINE(NI, rawget_141358)(Table141032 t, NimStringDesc* key, NI* hc);
N_NIMCALL(NI, hash_105827)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell47905*, usrtocell_52040)(void* usr);
static N_INLINE(void, rtladdzct_53601)(Cell47905* c);
N_NOINLINE(void, addzct_52017)(Cellseq47921* s, Cell47905* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, ispoweroftwo_114225)(NI x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, TMP358)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI, rawget_141854)(Table141657 t, NimStringDesc* key, NI* hc);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, enlarge_141882)(Table141657* t);
static N_INLINE(NI, rawgetknownhc_141935)(Table141657 t, NimStringDesc* key, NI hc);
N_NIMCALL(void, rawinsert_141951)(Table141657* t, Keyvaluepairseq141660** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h);
N_NIMCALL(void, TMP373)(void* p, NI op);
static N_INLINE(NI, rawget_142244)(Table142087 t, NimStringDesc* key, NI* hc);
N_NIMCALL(void, enlarge_142272)(Table142087* t);
static N_INLINE(NI, rawgetknownhc_142325)(Table142087 t, NimStringDesc* key, NI hc);
N_NIMCALL(void, rawinsert_142341)(Table142087* t, Keyvaluepairseq142090** data, NimStringDesc* key, Option141225* val, NI hc, NI h);
N_NIMCALL(void, inittable_142749)(NI initialsize, Table141032* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX5BHEX5DHEX3D_142846)(Table141032* t, NimStringDesc* key, NI val);
N_NIMCALL(void, enlarge_142882)(Table141032* t);
static N_INLINE(NI, rawgetknownhc_142935)(Table141032 t, NimStringDesc* key, NI hc);
N_NIMCALL(void, rawinsert_142951)(Table141032* t, Keyvaluepairseq141035** data, NimStringDesc* key, NI val, NI hc, NI h);
STRING_LITERAL(TMP317, "\012  counter < length ", 20);
STRING_LITERAL(TMP352, "key not found: ", 15);
STRING_LITERAL(TMP356, "isPowerOfTwo(initialSize) ", 26);
extern TFrame* frameptr_19436;
TNimType NTI141038; /* KeyValuePair */
extern TNimType NTI105002; /* Hash */
extern TNimType NTI138; /* string */
extern TNimType NTI104; /* int */
TNimType NTI141035; /* KeyValuePairSeq */
extern TNimType NTI141604; /* ref KeyError */
extern TNimType NTI3448; /* KeyError */
extern Gcheap50418 gch_50459;
TNimType NTI141663; /* KeyValuePair */
TNimType NTI141660; /* KeyValuePairSeq */
TNimType NTI141657; /* Table */
TNimType NTI142093; /* KeyValuePair */
extern TNimType NTI141225; /* Option */
TNimType NTI142090; /* KeyValuePairSeq */
TNimType NTI142087; /* Table */
TNimType NTI141032; /* Table */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(NIM_BOOL, isempty_118259)(NI hcode) {
	NIM_BOOL result;
	nimfr("isEmpty", "tableimpl.nim")
	result = 0;
	nimln(15, "tableimpl.nim");
	result = (hcode == ((NI) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isfilled_118263)(NI hcode) {
	NIM_BOOL result;
	nimfr("isFilled", "tableimpl.nim")
	result = 0;
	nimln(18, "tableimpl.nim");
	nimln(344, "system.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustrehash_118268)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP318;
	NI TMP319;
	NI TMP320;
	nimfr("mustRehash", "tableimpl.nim")
	result = 0;
	nimln(24, "tableimpl.nim");
	{
		if (!!((counter < length))) goto LA3;
		failedassertimpl_90839(((NimStringDesc*) &TMP317));
	}
	LA3: ;
	nimln(25, "tableimpl.nim");
	LOC5 = 0;
	TMP318 = mulInt(length, ((NI) 2));
	TMP319 = mulInt(counter, ((NI) 3));
	LOC5 = ((NI)(TMP318) < (NI)(TMP319));
	if (LOC5) goto LA6;
	TMP320 = subInt(length, counter);
	LOC5 = ((NI)(TMP320) < ((NI) 4));
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_118401)(NI h, NI maxhash) {
	NI result;
	NI TMP321;
	nimfr("nextTry", "tableimpl.nim")
	result = 0;
	nimln(28, "tableimpl.nim");
	TMP321 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TMP321) & maxhash);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, rightsize_118532)(NI count) {
	NI result;
	NI TMP322;
	NI TMP323;
	NI TMP324;
	nimfr("rightSize", "tables.nim")
	result = 0;
	nimln(95, "tables.nim");
	TMP322 = mulInt(((NI) (count)), ((NI) 3));
	TMP323 = divInt(((NI) ((NI)(TMP322))), ((NI) 2));
	TMP324 = addInt(((NI) ((NI)(TMP323))), ((NI) 4));
	result = nextpoweroftwo_114229(((NI) ((NI)(TMP324))));
	popFrame();
	return result;
}
N_NIMCALL(void, TMP341)(void* p, NI op) {
	Keyvaluepairseq141035* a;
	NI LOC1;
	a = (Keyvaluepairseq141035*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, rawget_141358)(Table141032 t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TMP350;
	nimfr("rawGet", "tableimpl.nim")
{	result = 0;
	nimln(43, "tableimpl.nim");
	(*hc) = hash_105827(key);
	nimln(44, "tableimpl.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC7 = 0;
			LOC7 = isfilled_118263(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = eqStrings(t.data->data[h].Field1, key);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_118401(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(40, "tableimpl.nim");
	TMP350 = subInt(((NI) -1), h);
	result = (NI)(TMP350);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, haskey_141346)(Table141032 t, NimStringDesc* key) {
	NIM_BOOL result;
	NI hc;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result = 0;
	hc = 0;
	nimln(150, "tables.nim");
	nimln(348, "system.nim");
	nimln(150, "tables.nim");
	LOC1 = 0;
	LOC1 = rawget_141358(t, key, (&hc));
	result = (((NI) 0) <= LOC1);
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(Cell47905*, usrtocell_52040)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(137, "gc.nim");
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_53601)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(218, "gc.nim");
	addzct_52017((&gch_50459.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(270, "gc.nim");
	{
		Cell47905* c;
		nimln(344, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(271, "gc.nim");
		c = usrtocell_52040(src);
		nimln(188, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(273, "gc.nim");
	{
		Cell47905* c;
		nimln(344, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(274, "gc.nim");
		c = usrtocell_52040((*dest));
		nimln(275, "gc.nim");
		{
			nimln(186, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(187, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(276, "gc.nim");
			rtladdzct_53601(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(277, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, HEX5BHEX5D_141378)(Table141032 t, NimStringDesc* key) {
	NI result;
	NI hc_141389;
	NI index_141391;
	nimfr("[]", "tables.nim")
	result = 0;
	hc_141389 = 0;
	nimln(106, "tables.nim");
	index_141391 = rawget_141358(t, key, (&hc_141389));
	nimln(107, "tables.nim");
	{
		nimln(348, "system.nim");
		if (!(((NI) 0) <= index_141391)) goto LA3;
		nimln(107, "tables.nim");
		if ((NU)(index_141391) >= (NU)(t.data->Sup.len)) raiseIndexError();
		result = t.data->data[index_141391].Field2;
	}
	goto LA1;
	LA3: ;
	{
		Keyerror3448* e_141603;
		NimStringDesc* LOC6;
		e_141603 = 0;
		nimln(2509, "system.nim");
		e_141603 = (Keyerror3448*) newObj((&NTI141604), sizeof(Keyerror3448));
		(*e_141603).Sup.Sup.Sup.m_type = (&NTI3448);
		nimln(2510, "system.nim");
		nimln(110, "tables.nim");
		LOC6 = 0;
		LOC6 = rawNewString(key->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &TMP352));
appendString(LOC6, key);
		asgnRefNoCycle((void**) (&(*e_141603).Sup.Sup.message), LOC6);
		raiseException((Exception*)e_141603, "KeyError");
	}
	LA1: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP358)(void* p, NI op) {
	Keyvaluepairseq141660* a;
	NI LOC1;
	a = (Keyvaluepairseq141660*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

N_NIMCALL(void, inittable_141677)(NI initialsize, Table141657* Result) {
	nimfr("initTable", "tables.nim")
	nimln(222, "tables.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ispoweroftwo_114225(initialsize);
		if (!!(LOC3)) goto LA4;
		failedassertimpl_90839(((NimStringDesc*) &TMP356));
	}
	LA4: ;
	nimln(223, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln(224, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (Keyvaluepairseq141660*) newSeq((&NTI141660), ((NI)chckRange(initialsize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

static N_INLINE(NI, rawget_141854)(Table141657 t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TMP359;
	nimfr("rawGet", "tableimpl.nim")
{	result = 0;
	nimln(43, "tableimpl.nim");
	(*hc) = hash_105827(key);
	nimln(44, "tableimpl.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC7 = 0;
			LOC7 = isfilled_118263(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = eqStrings(t.data->data[h].Field1, key);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_118401(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(40, "tableimpl.nim");
	TMP359 = subInt(((NI) -1), h);
	result = (NI)(TMP359);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47905* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(252, "gc.nim");
	c = usrtocell_52040(p);
	nimln(254, "gc.nim");
	{
		nimln(186, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(187, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(255, "gc.nim");
		rtladdzct_53601(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(NI, rawgetknownhc_141935)(Table141657 t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI TMP361;
	nimfr("rawGetKnownHC", "tableimpl.nim")
{	result = 0;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = isfilled_118263(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t.data->data[h].Field1, key);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_118401(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(40, "tableimpl.nim");
	TMP361 = subInt(((NI) -1), h);
	result = (NI)(TMP361);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_141951)(Table141657* t, Keyvaluepairseq141660** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h) {
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("rawInsert", "tableimpl.nim")
	nimln(58, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC1 = 0;
	LOC1 = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(59, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC2 = 0;
	LOC2 = (*data)->data[h].Field2; (*data)->data[h].Field2 = copyStringRC1(val);
	if (LOC2) nimGCunrefNoCycle(LOC2);
	nimln(60, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_NIMCALL(void, enlarge_141882)(Table141657* t) {
	Keyvaluepairseq141660* n;
	NI TMP360;
	Keyvaluepairseq141660* LOC1;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(188, "tables.nim");
	TMP360 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (Keyvaluepairseq141660*) newSeq((&NTI141660), ((NI)chckRange((NI)(TMP360), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(189, "tables.nim");
	LOC1 = 0;
	LOC1 = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = LOC1;
	{
		NI i_141933;
		NI HEX3Atmp_141974;
		NI res_141977;
		i_141933 = 0;
		HEX3Atmp_141974 = 0;
		nimln(190, "tables.nim");
		HEX3Atmp_141974 = (n ? (n->Sup.len-1) : -1);
		nimln(1873, "system.nim");
		res_141977 = ((NI) 0);
		{
			nimln(1874, "system.nim");
			while (1) {
				NI TMP363;
				if (!(res_141977 <= HEX3Atmp_141974)) goto LA4;
				nimln(1875, "system.nim");
				i_141933 = res_141977;
				nimln(191, "tables.nim");
				{
					NIM_BOOL LOC7;
					NI j;
					NI LOC10;
					NI TMP362;
					if ((NU)(i_141933) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = isfilled_118263(n->data[i_141933].Field0);
					if (!LOC7) goto LA8;
					nimln(192, "tables.nim");
					if ((NU)(i_141933) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_141933) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC10 = 0;
					LOC10 = rawgetknownhc_141935((*t), n->data[i_141933].Field1, n->data[i_141933].Field0);
					TMP362 = subInt(((NI) -1), LOC10);
					j = (NI)(TMP362);
					nimln(193, "tables.nim");
					if ((NU)(i_141933) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_141933) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_141933) >= (NU)(n->Sup.len)) raiseIndexError();
					rawinsert_141951(t, (&(*t).data), n->data[i_141933].Field1, n->data[i_141933].Field2, n->data[i_141933].Field0, j);
				}
				LA8: ;
				nimln(1889, "system.nim");
				TMP363 = addInt(res_141977, ((NI) 1));
				res_141977 = (NI)(TMP363);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_141840)(Table141657* t, NimStringDesc* key, NimStringDesc* val) {
	NI hc;
	NI index;
	nimfr("[]=", "tables.nim")
	hc = 0;
	nimln(92, "tableimpl.nim");
	index = rawget_141854((*t), key, (&hc));
	nimln(93, "tableimpl.nim");
	{
		NimStringDesc* LOC5;
		nimln(348, "system.nim");
		if (!(((NI) 0) <= index)) goto LA3;
		nimln(93, "tableimpl.nim");
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = (*t).data->data[index].Field2; (*t).data->data[index].Field2 = copyStringRC1(val);
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP364;
		NI TMP365;
		nimln(83, "tableimpl.nim");
		{
			NIM_BOOL LOC9;
			nimln(84, "tables.nim");
			LOC9 = 0;
			LOC9 = mustrehash_118268(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC9) goto LA10;
			nimln(84, "tableimpl.nim");
			enlarge_141882(t);
			nimln(85, "tableimpl.nim");
			index = rawgetknownhc_141935((*t), key, hc);
		}
		LA10: ;
		nimln(86, "tableimpl.nim");
		TMP364 = subInt(((NI) -1), index);
		index = (NI)(TMP364);
		nimln(87, "tableimpl.nim");
		rawinsert_141951(t, (&(*t).data), key, val, hc, index);
		nimln(88, "tableimpl.nim");
		TMP365 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP365);
	}
	LA1: ;
	popFrame();
}
N_NIMCALL(void, TMP373)(void* p, NI op) {
	Keyvaluepairseq142090* a;
	NI LOC1;
	a = (Keyvaluepairseq142090*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

N_NIMCALL(void, inittable_142112)(NI initialsize, Table142087* Result) {
	nimfr("initTable", "tables.nim")
	nimln(222, "tables.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ispoweroftwo_114225(initialsize);
		if (!!(LOC3)) goto LA4;
		failedassertimpl_90839(((NimStringDesc*) &TMP356));
	}
	LA4: ;
	nimln(223, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln(224, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (Keyvaluepairseq142090*) newSeq((&NTI142090), ((NI)chckRange(initialsize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

static N_INLINE(NI, rawget_142244)(Table142087 t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TMP374;
	nimfr("rawGet", "tableimpl.nim")
{	result = 0;
	nimln(43, "tableimpl.nim");
	(*hc) = hash_105827(key);
	nimln(44, "tableimpl.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC7 = 0;
			LOC7 = isfilled_118263(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = eqStrings(t.data->data[h].Field1, key);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_118401(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(40, "tableimpl.nim");
	TMP374 = subInt(((NI) -1), h);
	result = (NI)(TMP374);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawgetknownhc_142325)(Table142087 t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI TMP376;
	nimfr("rawGetKnownHC", "tableimpl.nim")
{	result = 0;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = isfilled_118263(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t.data->data[h].Field1, key);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_118401(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(40, "tableimpl.nim");
	TMP376 = subInt(((NI) -1), h);
	result = (NI)(TMP376);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_142341)(Table142087* t, Keyvaluepairseq142090** data, NimStringDesc* key, Option141225* val, NI hc, NI h) {
	NimStringDesc* LOC1;
	nimfr("rawInsert", "tableimpl.nim")
	nimln(58, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC1 = 0;
	LOC1 = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(59, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field2 = (*val);
	nimln(60, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_NIMCALL(void, enlarge_142272)(Table142087* t) {
	Keyvaluepairseq142090* n;
	NI TMP375;
	Keyvaluepairseq142090* LOC1;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(188, "tables.nim");
	TMP375 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (Keyvaluepairseq142090*) newSeq((&NTI142090), ((NI)chckRange((NI)(TMP375), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(189, "tables.nim");
	LOC1 = 0;
	LOC1 = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = LOC1;
	{
		NI i_142323;
		NI HEX3Atmp_142364;
		NI res_142367;
		i_142323 = 0;
		HEX3Atmp_142364 = 0;
		nimln(190, "tables.nim");
		HEX3Atmp_142364 = (n ? (n->Sup.len-1) : -1);
		nimln(1873, "system.nim");
		res_142367 = ((NI) 0);
		{
			nimln(1874, "system.nim");
			while (1) {
				NI TMP378;
				if (!(res_142367 <= HEX3Atmp_142364)) goto LA4;
				nimln(1875, "system.nim");
				i_142323 = res_142367;
				nimln(191, "tables.nim");
				{
					NIM_BOOL LOC7;
					NI j;
					NI LOC10;
					NI TMP377;
					if ((NU)(i_142323) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = isfilled_118263(n->data[i_142323].Field0);
					if (!LOC7) goto LA8;
					nimln(192, "tables.nim");
					if ((NU)(i_142323) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_142323) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC10 = 0;
					LOC10 = rawgetknownhc_142325((*t), n->data[i_142323].Field1, n->data[i_142323].Field0);
					TMP377 = subInt(((NI) -1), LOC10);
					j = (NI)(TMP377);
					nimln(193, "tables.nim");
					if ((NU)(i_142323) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_142323) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_142323) >= (NU)(n->Sup.len)) raiseIndexError();
					rawinsert_142341(t, (&(*t).data), n->data[i_142323].Field1, (&n->data[i_142323].Field2), n->data[i_142323].Field0, j);
				}
				LA8: ;
				nimln(1889, "system.nim");
				TMP378 = addInt(res_142367, ((NI) 1));
				res_142367 = (NI)(TMP378);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_142230)(Table142087* t, NimStringDesc* key, Option141225* val) {
	NI hc;
	NI index;
	nimfr("[]=", "tables.nim")
	hc = 0;
	nimln(92, "tableimpl.nim");
	index = rawget_142244((*t), key, (&hc));
	nimln(93, "tableimpl.nim");
	{
		nimln(348, "system.nim");
		if (!(((NI) 0) <= index)) goto LA3;
		nimln(93, "tableimpl.nim");
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		(*t).data->data[index].Field2 = (*val);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP379;
		NI TMP380;
		nimln(83, "tableimpl.nim");
		{
			NIM_BOOL LOC8;
			nimln(84, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_118268(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC8) goto LA9;
			nimln(84, "tableimpl.nim");
			enlarge_142272(t);
			nimln(85, "tableimpl.nim");
			index = rawgetknownhc_142325((*t), key, hc);
		}
		LA9: ;
		nimln(86, "tableimpl.nim");
		TMP379 = subInt(((NI) -1), index);
		index = (NI)(TMP379);
		nimln(87, "tableimpl.nim");
		rawinsert_142341(t, (&(*t).data), key, val, hc, index);
		nimln(88, "tableimpl.nim");
		TMP380 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP380);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, inittable_142749)(NI initialsize, Table141032* Result) {
	nimfr("initTable", "tables.nim")
	nimln(222, "tables.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ispoweroftwo_114225(initialsize);
		if (!!(LOC3)) goto LA4;
		failedassertimpl_90839(((NimStringDesc*) &TMP356));
	}
	LA4: ;
	nimln(223, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln(224, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (Keyvaluepairseq141035*) newSeq((&NTI141035), ((NI)chckRange(initialsize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

static N_INLINE(NI, rawgetknownhc_142935)(Table141032 t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI TMP390;
	nimfr("rawGetKnownHC", "tableimpl.nim")
{	result = 0;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = isfilled_118263(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t.data->data[h].Field1, key);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_118401(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(40, "tableimpl.nim");
	TMP390 = subInt(((NI) -1), h);
	result = (NI)(TMP390);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_142951)(Table141032* t, Keyvaluepairseq141035** data, NimStringDesc* key, NI val, NI hc, NI h) {
	NimStringDesc* LOC1;
	nimfr("rawInsert", "tableimpl.nim")
	nimln(58, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC1 = 0;
	LOC1 = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(59, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field2 = val;
	nimln(60, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_NIMCALL(void, enlarge_142882)(Table141032* t) {
	Keyvaluepairseq141035* n;
	NI TMP389;
	Keyvaluepairseq141035* LOC1;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(188, "tables.nim");
	TMP389 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (Keyvaluepairseq141035*) newSeq((&NTI141035), ((NI)chckRange((NI)(TMP389), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(189, "tables.nim");
	LOC1 = 0;
	LOC1 = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = LOC1;
	{
		NI i_142933;
		NI HEX3Atmp_142974;
		NI res_142977;
		i_142933 = 0;
		HEX3Atmp_142974 = 0;
		nimln(190, "tables.nim");
		HEX3Atmp_142974 = (n ? (n->Sup.len-1) : -1);
		nimln(1873, "system.nim");
		res_142977 = ((NI) 0);
		{
			nimln(1874, "system.nim");
			while (1) {
				NI TMP392;
				if (!(res_142977 <= HEX3Atmp_142974)) goto LA4;
				nimln(1875, "system.nim");
				i_142933 = res_142977;
				nimln(191, "tables.nim");
				{
					NIM_BOOL LOC7;
					NI j;
					NI LOC10;
					NI TMP391;
					if ((NU)(i_142933) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = isfilled_118263(n->data[i_142933].Field0);
					if (!LOC7) goto LA8;
					nimln(192, "tables.nim");
					if ((NU)(i_142933) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_142933) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC10 = 0;
					LOC10 = rawgetknownhc_142935((*t), n->data[i_142933].Field1, n->data[i_142933].Field0);
					TMP391 = subInt(((NI) -1), LOC10);
					j = (NI)(TMP391);
					nimln(193, "tables.nim");
					if ((NU)(i_142933) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_142933) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_142933) >= (NU)(n->Sup.len)) raiseIndexError();
					rawinsert_142951(t, (&(*t).data), n->data[i_142933].Field1, n->data[i_142933].Field2, n->data[i_142933].Field0, j);
				}
				LA8: ;
				nimln(1889, "system.nim");
				TMP392 = addInt(res_142977, ((NI) 1));
				res_142977 = (NI)(TMP392);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_142846)(Table141032* t, NimStringDesc* key, NI val) {
	NI hc;
	NI index;
	nimfr("[]=", "tables.nim")
	hc = 0;
	nimln(92, "tableimpl.nim");
	index = rawget_141358((*t), key, (&hc));
	nimln(93, "tableimpl.nim");
	{
		nimln(348, "system.nim");
		if (!(((NI) 0) <= index)) goto LA3;
		nimln(93, "tableimpl.nim");
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		(*t).data->data[index].Field2 = val;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP393;
		NI TMP394;
		nimln(83, "tableimpl.nim");
		{
			NIM_BOOL LOC8;
			nimln(84, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_118268(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC8) goto LA9;
			nimln(84, "tableimpl.nim");
			enlarge_142882(t);
			nimln(85, "tableimpl.nim");
			index = rawgetknownhc_142935((*t), key, hc);
		}
		LA9: ;
		nimln(86, "tableimpl.nim");
		TMP393 = subInt(((NI) -1), index);
		index = (NI)(TMP393);
		nimln(87, "tableimpl.nim");
		rawinsert_142951(t, (&(*t).data), key, val, hc, index);
		nimln(88, "tableimpl.nim");
		TMP394 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP394);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, totable_142738)(TY142743* pairs, NI pairsLen0, Table141032* Result) {
	NI LOC1;
	nimfr("toTable", "tables.nim")
	nimln(229, "tables.nim");
	LOC1 = 0;
	LOC1 = rightsize_118532(((NI)chckRange(pairsLen0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI141032));
	inittable_142749(LOC1, Result);
	{
		NimStringDesc* key_142843;
		NI val_142844;
		NI i_143029;
		key_142843 = 0;
		val_142844 = 0;
		nimln(1964, "system.nim");
		i_143029 = ((NI) 0);
		{
			nimln(1965, "system.nim");
			while (1) {
				NI TMP395;
				if (!(i_143029 < pairsLen0)) goto LA4;
				nimln(1966, "system.nim");
				if ((NU)(i_143029) >= (NU)(pairsLen0)) raiseIndexError();
				key_142843 = pairs[i_143029].Field0;
				if ((NU)(i_143029) >= (NU)(pairsLen0)) raiseIndexError();
				val_142844 = pairs[i_143029].Field1;
				nimln(230, "tables.nim");
				HEX5BHEX5DHEX3D_142846(Result, key_142843, val_142844);
				nimln(1967, "system.nim");
				TMP395 = addInt(i_143029, ((NI) 1));
				i_143029 = (NI)(TMP395);
			} LA4: ;
		}
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void) {
static TNimNode* TMP340[3];
static TNimNode* TMP357[3];
static TNimNode* TMP368[2];
static TNimNode* TMP370[3];
static TNimNode* TMP383[2];
static TNimNode* TMP388[2];
static TNimNode TMP148[21];
NTI141038.size = sizeof(Keyvaluepair141038);
NTI141038.kind = 18;
NTI141038.base = 0;
NTI141038.flags = 2;
TMP340[0] = &TMP148[1];
TMP148[1].kind = 1;
TMP148[1].offset = offsetof(Keyvaluepair141038, Field0);
TMP148[1].typ = (&NTI105002);
TMP148[1].name = "Field0";
TMP340[1] = &TMP148[2];
TMP148[2].kind = 1;
TMP148[2].offset = offsetof(Keyvaluepair141038, Field1);
TMP148[2].typ = (&NTI138);
TMP148[2].name = "Field1";
TMP340[2] = &TMP148[3];
TMP148[3].kind = 1;
TMP148[3].offset = offsetof(Keyvaluepair141038, Field2);
TMP148[3].typ = (&NTI104);
TMP148[3].name = "Field2";
TMP148[0].len = 3; TMP148[0].kind = 2; TMP148[0].sons = &TMP340[0];
NTI141038.node = &TMP148[0];
NTI141035.size = sizeof(Keyvaluepairseq141035*);
NTI141035.kind = 24;
NTI141035.base = (&NTI141038);
NTI141035.flags = 2;
NTI141035.marker = TMP341;
NTI141663.size = sizeof(Keyvaluepair141663);
NTI141663.kind = 18;
NTI141663.base = 0;
NTI141663.flags = 2;
TMP357[0] = &TMP148[5];
TMP148[5].kind = 1;
TMP148[5].offset = offsetof(Keyvaluepair141663, Field0);
TMP148[5].typ = (&NTI105002);
TMP148[5].name = "Field0";
TMP357[1] = &TMP148[6];
TMP148[6].kind = 1;
TMP148[6].offset = offsetof(Keyvaluepair141663, Field1);
TMP148[6].typ = (&NTI138);
TMP148[6].name = "Field1";
TMP357[2] = &TMP148[7];
TMP148[7].kind = 1;
TMP148[7].offset = offsetof(Keyvaluepair141663, Field2);
TMP148[7].typ = (&NTI138);
TMP148[7].name = "Field2";
TMP148[4].len = 3; TMP148[4].kind = 2; TMP148[4].sons = &TMP357[0];
NTI141663.node = &TMP148[4];
NTI141660.size = sizeof(Keyvaluepairseq141660*);
NTI141660.kind = 24;
NTI141660.base = (&NTI141663);
NTI141660.flags = 2;
NTI141660.marker = TMP358;
NTI141657.size = sizeof(Table141657);
NTI141657.kind = 18;
NTI141657.base = 0;
NTI141657.flags = 2;
TMP368[0] = &TMP148[9];
TMP148[9].kind = 1;
TMP148[9].offset = offsetof(Table141657, data);
TMP148[9].typ = (&NTI141660);
TMP148[9].name = "data";
TMP368[1] = &TMP148[10];
TMP148[10].kind = 1;
TMP148[10].offset = offsetof(Table141657, counter);
TMP148[10].typ = (&NTI104);
TMP148[10].name = "counter";
TMP148[8].len = 2; TMP148[8].kind = 2; TMP148[8].sons = &TMP368[0];
NTI141657.node = &TMP148[8];
NTI142093.size = sizeof(Keyvaluepair142093);
NTI142093.kind = 18;
NTI142093.base = 0;
NTI142093.flags = 2;
TMP370[0] = &TMP148[12];
TMP148[12].kind = 1;
TMP148[12].offset = offsetof(Keyvaluepair142093, Field0);
TMP148[12].typ = (&NTI105002);
TMP148[12].name = "Field0";
TMP370[1] = &TMP148[13];
TMP148[13].kind = 1;
TMP148[13].offset = offsetof(Keyvaluepair142093, Field1);
TMP148[13].typ = (&NTI138);
TMP148[13].name = "Field1";
TMP370[2] = &TMP148[14];
TMP148[14].kind = 1;
TMP148[14].offset = offsetof(Keyvaluepair142093, Field2);
TMP148[14].typ = (&NTI141225);
TMP148[14].name = "Field2";
TMP148[11].len = 3; TMP148[11].kind = 2; TMP148[11].sons = &TMP370[0];
NTI142093.node = &TMP148[11];
NTI142090.size = sizeof(Keyvaluepairseq142090*);
NTI142090.kind = 24;
NTI142090.base = (&NTI142093);
NTI142090.flags = 2;
NTI142090.marker = TMP373;
NTI142087.size = sizeof(Table142087);
NTI142087.kind = 18;
NTI142087.base = 0;
NTI142087.flags = 2;
TMP383[0] = &TMP148[16];
TMP148[16].kind = 1;
TMP148[16].offset = offsetof(Table142087, data);
TMP148[16].typ = (&NTI142090);
TMP148[16].name = "data";
TMP383[1] = &TMP148[17];
TMP148[17].kind = 1;
TMP148[17].offset = offsetof(Table142087, counter);
TMP148[17].typ = (&NTI104);
TMP148[17].name = "counter";
TMP148[15].len = 2; TMP148[15].kind = 2; TMP148[15].sons = &TMP383[0];
NTI142087.node = &TMP148[15];
NTI141032.size = sizeof(Table141032);
NTI141032.kind = 18;
NTI141032.base = 0;
NTI141032.flags = 2;
TMP388[0] = &TMP148[19];
TMP148[19].kind = 1;
TMP148[19].offset = offsetof(Table141032, data);
TMP148[19].typ = (&NTI141035);
TMP148[19].name = "data";
TMP388[1] = &TMP148[20];
TMP148[20].kind = 1;
TMP148[20].offset = offsetof(Table141032, counter);
TMP148[20].typ = (&NTI104);
TMP148[20].name = "counter";
TMP148[18].len = 2; TMP148[18].kind = 2; TMP148[18].sons = &TMP388[0];
NTI141032.node = &TMP148[18];
}

