/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/adminuser/Nim/lib -o /home/adminuser/awknim/nimcache/stdlib_pcre.o /home/adminuser/awknim/nimcache/stdlib_pcre.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Pcre94258 Pcre94258;
typedef struct Extradata94270 Extradata94270;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, TY94698) (Pcre94258* code, Extradata94270* extra, int what, void* where);
typedef N_CDECL_PTR(int, TY94624) (int what, void* where);
typedef N_CDECL_PTR(void, TY94692) (NCSTRING stringptr);
typedef N_CDECL_PTR(void, TY94759) (Extradata94270* extra);
struct  Pcre94258  {
char dummy;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  Extradata94270  {
long flags;
void* studydata;
long matchlimit;
void* calloutdata;
void* tables;
long matchlimitrecursion;
void* mark;
void* executablejit;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(Pcre94258*, TY94602) (NCSTRING pattern, int options, NCSTRING* errptr, int* erroffset, void* tableptr);
typedef N_CDECL_PTR(Extradata94270*, TY94751) (Pcre94258* code, int options, NCSTRING* errptr);
typedef N_CDECL_PTR(int, TY94664) (Pcre94258* code, Extradata94270* extra, NCSTRING subject, int length, int startoffset, int options, int* ovector, int ovecsize);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP334, "libpcre.so.3", 12);
STRING_LITERAL(TMP335, "libpcre.so.1", 12);
STRING_LITERAL(TMP336, "libpcre.so", 10);
STRING_LITERAL(TMP337, "libpcre.so(.3|.1|)", 18);
static void* TMP333;
TY94698 Dl_94697;
TY94624 Dl_94623;
TY94692 Dl_94691;
TY94759 Dl_94758;
TNimType NTI94258; /* Pcre */
TNimType NTI94699; /* ptr Pcre */
TNimType NTI94270; /* ExtraData */
extern TNimType NTI7093; /* clong */
extern TNimType NTI142; /* pointer */
TNimType NTI94701; /* ptr ExtraData */
TY94602 Dl_94601;
TY94751 Dl_94750;
TY94664 Dl_94663;
extern TFrame* frameptr_19436;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreInit000)(void) {
	nimfr("pcre", "pcre.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_pcreDatInit000)(void) {
static TNimNode* TMP442[8];
static TNimNode TMP144[10];
NTI94258.size = sizeof(Pcre94258);
NTI94258.kind = 18;
NTI94258.base = 0;
NTI94258.flags = 3;
TMP144[0].len = 0; TMP144[0].kind = 2;
NTI94258.node = &TMP144[0];
NTI94699.size = sizeof(Pcre94258*);
NTI94699.kind = 21;
NTI94699.base = (&NTI94258);
NTI94699.flags = 3;
NTI94270.size = sizeof(Extradata94270);
NTI94270.kind = 18;
NTI94270.base = 0;
NTI94270.flags = 3;
TMP442[0] = &TMP144[2];
TMP144[2].kind = 1;
TMP144[2].offset = offsetof(Extradata94270, flags);
TMP144[2].typ = (&NTI7093);
TMP144[2].name = "flags";
TMP442[1] = &TMP144[3];
TMP144[3].kind = 1;
TMP144[3].offset = offsetof(Extradata94270, studydata);
TMP144[3].typ = (&NTI142);
TMP144[3].name = "study_data";
TMP442[2] = &TMP144[4];
TMP144[4].kind = 1;
TMP144[4].offset = offsetof(Extradata94270, matchlimit);
TMP144[4].typ = (&NTI7093);
TMP144[4].name = "match_limit";
TMP442[3] = &TMP144[5];
TMP144[5].kind = 1;
TMP144[5].offset = offsetof(Extradata94270, calloutdata);
TMP144[5].typ = (&NTI142);
TMP144[5].name = "callout_data";
TMP442[4] = &TMP144[6];
TMP144[6].kind = 1;
TMP144[6].offset = offsetof(Extradata94270, tables);
TMP144[6].typ = (&NTI142);
TMP144[6].name = "tables";
TMP442[5] = &TMP144[7];
TMP144[7].kind = 1;
TMP144[7].offset = offsetof(Extradata94270, matchlimitrecursion);
TMP144[7].typ = (&NTI7093);
TMP144[7].name = "match_limit_recursion";
TMP442[6] = &TMP144[8];
TMP144[8].kind = 1;
TMP144[8].offset = offsetof(Extradata94270, mark);
TMP144[8].typ = (&NTI142);
TMP144[8].name = "mark";
TMP442[7] = &TMP144[9];
TMP144[9].kind = 1;
TMP144[9].offset = offsetof(Extradata94270, executablejit);
TMP144[9].typ = (&NTI142);
TMP144[9].name = "executable_jit";
TMP144[1].len = 8; TMP144[1].kind = 2; TMP144[1].sons = &TMP442[0];
NTI94270.node = &TMP144[1];
NTI94701.size = sizeof(Extradata94270*);
NTI94701.kind = 21;
NTI94701.base = (&NTI94270);
NTI94701.flags = 3;
if (!((TMP333 = nimLoadLibrary((NimStringDesc*) &TMP334))
||(TMP333 = nimLoadLibrary((NimStringDesc*) &TMP335))
||(TMP333 = nimLoadLibrary((NimStringDesc*) &TMP336))
)) nimLoadLibraryError((NimStringDesc*) &TMP337);
	Dl_94697 = (TY94698) nimGetProcAddr(TMP333, "pcre_fullinfo");
	Dl_94623 = (TY94624) nimGetProcAddr(TMP333, "pcre_config");
	Dl_94691 = (TY94692) nimGetProcAddr(TMP333, "pcre_free_substring");
	Dl_94758 = (TY94759) nimGetProcAddr(TMP333, "pcre_free_study");
	Dl_94601 = (TY94602) nimGetProcAddr(TMP333, "pcre_compile");
	Dl_94750 = (TY94751) nimGetProcAddr(TMP333, "pcre_study");
	Dl_94663 = (TY94664) nimGetProcAddr(TMP333, "pcre_exec");
}

