/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/adminuser/Nim/lib -o /home/adminuser/awknim/nimcache/stdlib_hashes.o /home/adminuser/awknim/nimcache/stdlib_hashes.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(NI, HEX21HEX26_105004)(NI h, NI val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, HEX21HEX24_105027)(NI h);
N_NIMCALL(NI, hashdata_105049)(void* data, NI size);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, hash_105401)(void* x);
static N_INLINE(NI, hash_105801)(NI x);
static N_INLINE(NI, hash_105805)(NI64 x);
static N_INLINE(NI, hash_105809)(NIM_CHAR x);
N_NIMCALL(NI, hash_105827)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, hash_105859)(NimStringDesc* sbuf, NI spos, NI epos);
N_NIMCALL(NI, hashignorestyle_105892)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_104004)(NCSTRING cs, NI i);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NI, hashignorestyle_105975)(NimStringDesc* sbuf, NI spos, NI epos);
N_NIMCALL(NI, hashignorecase_106059)(NimStringDesc* x);
N_NIMCALL(NI, hashignorecase_106130)(NimStringDesc* sbuf, NI spos, NI epos);
static N_INLINE(NI, hash_106202)(NF x);
extern TFrame* frameptr_19436;
TNimType NTI105002; /* Hash */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(NI, HEX21HEX26_105004)(NI h, NI val) {
	NI result;
	nimfr("!&", "hashes.nim")
	result = 0;
	nimln(53, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)(val));
	nimln(54, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(((NI) 10)))));
	nimln(55, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(((NI) 6))));
	popFrame();
	return result;
}

static N_INLINE(NI, HEX21HEX24_105027)(NI h) {
	NI result;
	nimfr("!$", "hashes.nim")
	result = 0;
	nimln(60, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)((NI)((NU64)(h) << (NU64)(((NI) 3)))));
	nimln(61, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(((NI) 11))));
	nimln(62, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(((NI) 15)))));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hashdata_105049)(void* data, NI size) {
	NI result;
	NI h;
	NCSTRING p;
	NI i;
	NI s;
	nimfr("hashData", "hashes.nim")
	result = 0;
	nimln(66, "hashes.nim");
	h = ((NI) 0);
	nimln(71, "hashes.nim");
	p = ((NCSTRING) (data));
	nimln(72, "hashes.nim");
	i = ((NI) 0);
	nimln(73, "hashes.nim");
	s = size;
	{
		nimln(74, "hashes.nim");
		while (1) {
			NI TMP160;
			NI TMP161;
			nimln(352, "system.nim");
			if (!(((NI) 0) < s)) goto LA2;
			nimln(75, "hashes.nim");
			h = HEX21HEX26_105004(h, ((NI) (((NU8)(p[i])))));
			nimln(76, "hashes.nim");
			TMP160 = addInt(i, ((NI) 1));
			i = (NI)(TMP160);
			nimln(77, "hashes.nim");
			TMP161 = subInt(s, ((NI) 1));
			s = (NI)(TMP161);
		} LA2: ;
	}
	nimln(78, "hashes.nim");
	result = HEX21HEX24_105027(h);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_105401)(void* x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(97, "hashes.nim");
	result = (NI)((NU64)(((NI) (x))) >> (NU64)(((NI) 3)));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_105801)(NI x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(109, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NI, hash_105805)(NI64 x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(113, "hashes.nim");
	result = ((NI) (((NI32)(NU32)(NU64)(x))));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_105809)(NIM_CHAR x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(117, "hashes.nim");
	result = ((NI) (((NU8)(x))));
	popFrame();
	return result;
}

N_NIMCALL(NI, hash_105827)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(125, "hashes.nim");
	h = ((NI) 0);
	{
		NI i_105841;
		NI HEX3Atmp_105852;
		NI TMP162;
		NI res_105855;
		i_105841 = 0;
		HEX3Atmp_105852 = 0;
		nimln(126, "hashes.nim");
		TMP162 = subInt((x ? x->Sup.len : 0), ((NI) 1));
		HEX3Atmp_105852 = (NI)(TMP162);
		nimln(1873, "system.nim");
		res_105855 = ((NI) 0);
		{
			nimln(1874, "system.nim");
			while (1) {
				NI TMP163;
				if (!(res_105855 <= HEX3Atmp_105852)) goto LA3;
				nimln(1875, "system.nim");
				i_105841 = res_105855;
				nimln(127, "hashes.nim");
				if ((NU)(i_105841) > (NU)(x->Sup.len)) raiseIndexError();
				h = HEX21HEX26_105004(h, ((NI) (((NU8)(x->data[i_105841])))));
				nimln(1894, "system.nim");
				TMP163 = addInt(res_105855, ((NI) 1));
				res_105855 = (NI)(TMP163);
			} LA3: ;
		}
	}
	nimln(128, "hashes.nim");
	result = HEX21HEX24_105027(h);
	popFrame();
	return result;
}

N_NIMCALL(NI, hash_105859)(NimStringDesc* sbuf, NI spos, NI epos) {
	NI result;
	NI h;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(135, "hashes.nim");
	h = ((NI) 0);
	{
		NI i_105875;
		NI res_105888;
		i_105875 = 0;
		nimln(1873, "system.nim");
		res_105888 = spos;
		{
			nimln(1874, "system.nim");
			while (1) {
				NI TMP164;
				if (!(res_105888 <= epos)) goto LA3;
				nimln(1875, "system.nim");
				i_105875 = res_105888;
				nimln(137, "hashes.nim");
				if ((NU)(i_105875) > (NU)(sbuf->Sup.len)) raiseIndexError();
				h = HEX21HEX26_105004(h, ((NI) (((NU8)(sbuf->data[i_105875])))));
				nimln(1894, "system.nim");
				TMP164 = addInt(res_105888, ((NI) 1));
				res_105888 = (NI)(TMP164);
			} LA3: ;
		}
	}
	nimln(138, "hashes.nim");
	result = HEX21HEX24_105027(h);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_104004)(NCSTRING cs, NI i) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NI TMP166;
	NI TMP167;
	nimfr("isMagicIdentSeparatorRune", "etcpriv.nim")
	result = 0;
	nimln(21, "etcpriv.nim");
	nimln(22, "etcpriv.nim");
	LOC1 = 0;
	nimln(21, "etcpriv.nim");
	LOC2 = 0;
	LOC2 = ((NU8)(cs[i]) == (NU8)(226));
	if (!(LOC2)) goto LA3;
	nimln(22, "etcpriv.nim");
	TMP166 = addInt(i, ((NI) 1));
	LOC2 = ((NU8)(cs[(NI)(TMP166)]) == (NU8)(128));
	LA3: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA4;
	nimln(23, "etcpriv.nim");
	TMP167 = addInt(i, ((NI) 2));
	LOC1 = ((NU8)(cs[(NI)(TMP167)]) == (NU8)(147));
	LA4: ;
	result = LOC1;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hashignorestyle_105892)(NimStringDesc* x) {
	NI result;
	NI h;
	NI i;
	NI xlen;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result = 0;
	nimln(142, "hashes.nim");
	h = ((NI) 0);
	nimln(143, "hashes.nim");
	i = ((NI) 0);
	nimln(144, "hashes.nim");
	xlen = (x ? x->Sup.len : 0);
	{
		nimln(145, "hashes.nim");
		while (1) {
			NIM_CHAR c;
			if (!(i < xlen)) goto LA2;
			nimln(146, "hashes.nim");
			if ((NU)(i) > (NU)(x->Sup.len)) raiseIndexError();
			c = x->data[i];
			nimln(147, "hashes.nim");
			{
				NI TMP165;
				if (!((NU8)(c) == (NU8)(95))) goto LA5;
				nimln(148, "hashes.nim");
				TMP165 = addInt(i, ((NI) 1));
				i = (NI)(TMP165);
			}
			goto LA3;
			LA5: ;
			{
				NIM_BOOL LOC8;
				NI TMP168;
				nimln(149, "hashes.nim");
				LOC8 = 0;
				LOC8 = ismagicidentseparatorrune_104004(x->data, i);
				if (!LOC8) goto LA9;
				nimln(150, "hashes.nim");
				TMP168 = addInt(i, ((NI) 3));
				i = (NI)(TMP168);
			}
			goto LA3;
			LA9: ;
			{
				NI TMP170;
				nimln(152, "hashes.nim");
				{
					NI TMP169;
					nimln(1093, "system.nim");
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA14;
					nimln(153, "hashes.nim");
					TMP169 = addInt(((NI) (((NU8)(c)))), ((NI) 32));
					c = ((NIM_CHAR) (((NI)chckRange((NI)(TMP169), ((NI) 0), ((NI) 255)))));
				}
				LA14: ;
				nimln(154, "hashes.nim");
				h = HEX21HEX26_105004(h, ((NI) (((NU8)(c)))));
				nimln(155, "hashes.nim");
				TMP170 = addInt(i, ((NI) 1));
				i = (NI)(TMP170);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(157, "hashes.nim");
	result = HEX21HEX24_105027(h);
	popFrame();
	return result;
}

N_NIMCALL(NI, hashignorestyle_105975)(NimStringDesc* sbuf, NI spos, NI epos) {
	NI result;
	NI h;
	NI i;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result = 0;
	nimln(165, "hashes.nim");
	h = ((NI) 0);
	nimln(166, "hashes.nim");
	i = spos;
	{
		nimln(167, "hashes.nim");
		while (1) {
			NIM_CHAR c;
			if (!(i <= epos)) goto LA2;
			nimln(168, "hashes.nim");
			if ((NU)(i) > (NU)(sbuf->Sup.len)) raiseIndexError();
			c = sbuf->data[i];
			nimln(169, "hashes.nim");
			{
				NI TMP171;
				if (!((NU8)(c) == (NU8)(95))) goto LA5;
				nimln(170, "hashes.nim");
				TMP171 = addInt(i, ((NI) 1));
				i = (NI)(TMP171);
			}
			goto LA3;
			LA5: ;
			{
				NIM_BOOL LOC8;
				NI TMP172;
				nimln(171, "hashes.nim");
				LOC8 = 0;
				LOC8 = ismagicidentseparatorrune_104004(sbuf->data, i);
				if (!LOC8) goto LA9;
				nimln(172, "hashes.nim");
				TMP172 = addInt(i, ((NI) 3));
				i = (NI)(TMP172);
			}
			goto LA3;
			LA9: ;
			{
				NI TMP174;
				nimln(174, "hashes.nim");
				{
					NI TMP173;
					nimln(1093, "system.nim");
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA14;
					nimln(175, "hashes.nim");
					TMP173 = addInt(((NI) (((NU8)(c)))), ((NI) 32));
					c = ((NIM_CHAR) (((NI)chckRange((NI)(TMP173), ((NI) 0), ((NI) 255)))));
				}
				LA14: ;
				nimln(176, "hashes.nim");
				h = HEX21HEX26_105004(h, ((NI) (((NU8)(c)))));
				nimln(177, "hashes.nim");
				TMP174 = addInt(i, ((NI) 1));
				i = (NI)(TMP174);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(178, "hashes.nim");
	result = HEX21HEX24_105027(h);
	popFrame();
	return result;
}

N_NIMCALL(NI, hashignorecase_106059)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hashIgnoreCase", "hashes.nim")
	result = 0;
	nimln(182, "hashes.nim");
	h = ((NI) 0);
	{
		NI i_106073;
		NI HEX3Atmp_106123;
		NI TMP175;
		NI res_106126;
		i_106073 = 0;
		HEX3Atmp_106123 = 0;
		nimln(183, "hashes.nim");
		TMP175 = subInt((x ? x->Sup.len : 0), ((NI) 1));
		HEX3Atmp_106123 = (NI)(TMP175);
		nimln(1873, "system.nim");
		res_106126 = ((NI) 0);
		{
			nimln(1874, "system.nim");
			while (1) {
				NIM_CHAR c;
				NI TMP177;
				if (!(res_106126 <= HEX3Atmp_106123)) goto LA3;
				nimln(1875, "system.nim");
				i_106073 = res_106126;
				nimln(184, "hashes.nim");
				if ((NU)(i_106073) > (NU)(x->Sup.len)) raiseIndexError();
				c = x->data[i_106073];
				nimln(185, "hashes.nim");
				{
					NI TMP176;
					nimln(1093, "system.nim");
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA6;
					nimln(186, "hashes.nim");
					TMP176 = addInt(((NI) (((NU8)(c)))), ((NI) 32));
					c = ((NIM_CHAR) (((NI)chckRange((NI)(TMP176), ((NI) 0), ((NI) 255)))));
				}
				LA6: ;
				nimln(187, "hashes.nim");
				h = HEX21HEX26_105004(h, ((NI) (((NU8)(c)))));
				nimln(1894, "system.nim");
				TMP177 = addInt(res_106126, ((NI) 1));
				res_106126 = (NI)(TMP177);
			} LA3: ;
		}
	}
	nimln(188, "hashes.nim");
	result = HEX21HEX24_105027(h);
	popFrame();
	return result;
}

N_NIMCALL(NI, hashignorecase_106130)(NimStringDesc* sbuf, NI spos, NI epos) {
	NI result;
	NI h;
	nimfr("hashIgnoreCase", "hashes.nim")
	result = 0;
	nimln(196, "hashes.nim");
	h = ((NI) 0);
	{
		NI i_106146;
		NI res_106198;
		i_106146 = 0;
		nimln(1873, "system.nim");
		res_106198 = spos;
		{
			nimln(1874, "system.nim");
			while (1) {
				NIM_CHAR c;
				NI TMP179;
				if (!(res_106198 <= epos)) goto LA3;
				nimln(1875, "system.nim");
				i_106146 = res_106198;
				nimln(198, "hashes.nim");
				if ((NU)(i_106146) > (NU)(sbuf->Sup.len)) raiseIndexError();
				c = sbuf->data[i_106146];
				nimln(199, "hashes.nim");
				{
					NI TMP178;
					nimln(1093, "system.nim");
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA6;
					nimln(200, "hashes.nim");
					TMP178 = addInt(((NI) (((NU8)(c)))), ((NI) 32));
					c = ((NIM_CHAR) (((NI)chckRange((NI)(TMP178), ((NI) 0), ((NI) 255)))));
				}
				LA6: ;
				nimln(201, "hashes.nim");
				h = HEX21HEX26_105004(h, ((NI) (((NU8)(c)))));
				nimln(1894, "system.nim");
				TMP179 = addInt(res_106198, ((NI) 1));
				res_106198 = (NI)(TMP179);
			} LA3: ;
		}
	}
	nimln(202, "hashes.nim");
	result = HEX21HEX24_105027(h);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_106202)(NF x) {
	NI result;
	NF y;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(206, "hashes.nim");
	y = ((NF)(x) + (NF)(1.0000000000000000e+00));
	nimln(207, "hashes.nim");
	result = (*((NI*) ((&y))));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void) {
	nimfr("hashes", "hashes.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void) {
NTI105002.size = sizeof(NI);
NTI105002.kind = 31;
NTI105002.base = 0;
NTI105002.flags = 3;
}

