/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/adminuser/Nim/lib -o /home/adminuser/awknim/nimcache/test.o /home/adminuser/awknim/nimcache/test.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Cell47905 Cell47905;
typedef struct TNimType TNimType;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Gcheap50418 Gcheap50418;
typedef struct Gcstack50416 Gcstack50416;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50414 Gcstat50414;
typedef struct TY15805 TY15805;
typedef struct RegexHEX3Aobjecttype141019 RegexHEX3Aobjecttype141019;
typedef struct TNimNode TNimNode;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
typedef struct Pcre94258 Pcre94258;
typedef struct Extradata94270 Extradata94270;
typedef struct Table141032 Table141032;
typedef struct Keyvaluepairseq141035 Keyvaluepairseq141035;
typedef struct Keyvaluepair141038 Keyvaluepair141038;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30088  {
NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50418  {
Gcstack50416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50414 stat;
};
typedef NI TY147217[2];
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  Gcstack50416  {
Gcstack50416* prev;
Gcstack50416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30019[8];
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {
NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {
TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct  Table141032  {
Keyvaluepairseq141035* data;
NI counter;
};
struct  RegexHEX3Aobjecttype141019  {
NimStringDesc* pattern;
Pcre94258* pcreobj;
Extradata94270* pcreextra;
Table141032 capturenametoid;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
struct  Pcre94258  {
char dummy;
};
struct  Extradata94270  {
long flags;
void* studydata;
long matchlimit;
void* calloutdata;
void* tables;
long matchlimitrecursion;
void* mark;
void* executablejit;
};
struct Keyvaluepair141038 {
NI Field0;
NimStringDesc* Field1;
NI Field2;
};
struct TY15805 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq141035 {
  TGenericSeq Sup;
  Keyvaluepair141038 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell47905*, usrtocell_52040)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_53601)(Cell47905* c);
N_NOINLINE(void, addzct_52017)(Cellseq47921* s, Cell47905* c);
N_NIMCALL(NimStringDesc*, readfile_15466)(NimStringDesc* filename);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(NI, makediscardable_147211)(NI a);
N_NIMCALL(NI, match_145037)(NimStringDesc* source, NimStringDesc* pattern, NimStringDesc** dest);
N_NIMCALL(TY15805*, split_143894)(NimStringDesc* str, RegexHEX3Aobjecttype141019* pattern, NI maxsplit, NI start);
N_NIMCALL(RegexHEX3Aobjecttype141019*, re_143506)(NimStringDesc* pattern_143508);
N_NIMCALL(NIM_BOOL, HEX7E_145119)(NimStringDesc* source, NimStringDesc* pattern);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, substrawk_146832)(NimStringDesc* source, NI* a, NI aLen0);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_utilInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_utilDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typetraitsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typetraitsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_optionsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_optionsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nreInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nreDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_awknimInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_awknimDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, testInit000)(void);
NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void);
STRING_LITERAL(TMP581, "", 0);
STRING_LITERAL(TMP582, "data.txt", 8);
STRING_LITERAL(TMP583, "<a href=\"my text\">", 18);
STRING_LITERAL(TMP584, "(?s)\"", 5);
STRING_LITERAL(TMP585, "text", 4);
NimStringDesc* dest_147001;
extern TFrame* frameptr_19436;
extern Gcheap50418 gch_50459;
NimStringDesc* fp_147002;
TY15805* arr_147201;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(Cell47905*, usrtocell_52040)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(137, "gc.nim");
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_53601)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(218, "gc.nim");
	addzct_52017((&gch_50459.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47905* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(252, "gc.nim");
	c = usrtocell_52040(p);
	nimln(254, "gc.nim");
	{
		nimln(186, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(187, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(255, "gc.nim");
		rtladdzct_53601(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(270, "gc.nim");
	{
		Cell47905* c;
		nimln(344, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(271, "gc.nim");
		c = usrtocell_52040(src);
		nimln(188, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(273, "gc.nim");
	{
		Cell47905* c;
		nimln(344, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(274, "gc.nim");
		c = usrtocell_52040((*dest));
		nimln(275, "gc.nim");
		{
			nimln(186, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(187, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(276, "gc.nim");
			rtladdzct_53601(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(277, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, makediscardable_147211)(NI a) {
	NI result;
	nimfr("makeDiscardable", "awknim.nim")
	result = 0;
	nimln(95, "awknim.nim");
	result = a;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_pcreDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_timesDatInit000();
	stdlib_mathDatInit000();
	stdlib_tablesDatInit000();
	stdlib_utilDatInit000();
	stdlib_typetraitsDatInit000();
	stdlib_optionsDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_nreDatInit000();
	HEX00_awknimDatInit000();
	testDatInit000();
	stdlib_pcreInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_timesInit000();
	stdlib_mathInit000();
	stdlib_tablesInit000();
	stdlib_utilInit000();
	stdlib_typetraitsInit000();
	stdlib_optionsInit000();
	stdlib_unicodeInit000();
	stdlib_nreInit000();
	HEX00_awknimInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	testInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, testInit000)(void) {
	NimStringDesc* LOC1;
	nimfr("test", "test.nim")
	nimln(3, "test.nim");
	LOC1 = 0;
	LOC1 = dest_147001; dest_147001 = copyStringRC1(((NimStringDesc*) &TMP581));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(4, "test.nim");
	asgnRefNoCycle((void**) (&fp_147002), readfile_15466(((NimStringDesc*) &TMP582)));
	nimln(5, "test.nim");
	{
		NI LOC4;
		RegexHEX3Aobjecttype141019* LOC7;
		NI LOC8;
		nimln(352, "system.nim");
		nimln(5, "test.nim");
		LOC4 = 0;
		LOC4 = match_145037(fp_147002, ((NimStringDesc*) &TMP583), (&dest_147001));
		if (!(((NI) 0) < LOC4)) goto LA5;
		nimln(200, "awknim.nim");
		LOC7 = 0;
		LOC7 = re_143506(((NimStringDesc*) &TMP584));
		asgnRefNoCycle((void**) (&arr_147201), split_143894(dest_147001, LOC7, ((NI) -1), ((NI) 0)));
		nimln(201, "awknim.nim");
		LOC8 = 0;
		LOC8 = makediscardable_147211((arr_147201 ? arr_147201->Sup.len : 0));
		nimln(7, "test.nim");
		{
			NIM_BOOL LOC11;
			TY147217 LOC14;
			NI TMP586;
			NimStringDesc* LOC15;
			if ((NU)(((NI) 1)) >= (NU)(arr_147201->Sup.len)) raiseIndexError();
			LOC11 = 0;
			LOC11 = HEX7E_145119(arr_147201->data[((NI) 1)], ((NimStringDesc*) &TMP585));
			if (!LOC11) goto LA12;
			nimln(8, "test.nim");
			if ((NU)(((NI) 1)) >= (NU)(arr_147201->Sup.len)) raiseIndexError();
			LOC14[0] = ((NI) 3);
			if ((NU)(((NI) 1)) >= (NU)(arr_147201->Sup.len)) raiseIndexError();
			TMP586 = subInt((arr_147201->data[((NI) 1)] ? arr_147201->data[((NI) 1)]->Sup.len : 0), ((NI) 1));
			LOC14[1] = (NI)(TMP586);
			LOC15 = 0;
			LOC15 = substrawk_146832(arr_147201->data[((NI) 1)], LOC14, 2);
			printf("%s\012", LOC15? (LOC15)->data:"nil");
			fflush(stdout);
		}
		LA12: ;
	}
	LA5: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void) {
}

